//! Futamura-1 specialization of the mimas interpreter: given a compiled
//! [`Program`], emit one Rust fn per bytecode body — a `step_one` specialized to
//! that body's fixed op stream, with operands already folded to literals.
//!
//! The emitted module is consumed by `Vm::install_bc`:
//!
//! ```ignore
//! let (program, sources) = Vm::compile_parts(files, std_install)?;
//! let src = bcgen::emit(&program, "mimas::vm");   // the generated module
//! // ... write `src` into a crate that deps `mimas`, build it, and inside it:
//! vm.load_prebuilt(program, sources, std_install);
//! vm.install_bc(generated::bodies());
//! vm.run() // executes specialized bodies, interpreter for everything else
//! ```
//!
//! Two levels of specialization, both single-sourced against the interpreter:
//!
//! * **Ops.** Every op arm reproduces `step_one`'s statement-for-statement, and every *cold path
//!   inside* an arm tail-calls the same `bin_cold`/`branch_cold` helper the interpreter's own
//!   macros reach (with `code.ip` pre-advanced, since generated code never decodes). The `_ =>`
//!   catch-all delegates to `step` — the real `step_one` — for ops no emitter covers.
//! * **Registers.** A register whose writers all produce one scalar kind (int/float) gets a native
//!   Rust local shadowing it, *write-through*: every shadow update also stores the `Val` into
//!   `regs`, so `regs` stays authoritative and any op, call, native, or `step` fallback always sees
//!   the truth. A body entering with a shadowed register holding a non-scalar `Val` (a mistyped
//!   call argument, an uninitialized slot) bails that one op to `step` — the interpreter runs it
//!   verbatim and the program continues.
//!
//! Bodies loop internally: fuel, op budget, and the pause flag are consumed
//! per op exactly as `run_dispatch` does, and `Flow::Call`/`Flow::Return`/errors
//! end the body's turn for the driver's frame transitions.

use std::{
    collections::{HashMap, HashSet},
    fmt::Write,
};

use compile::{BlockTarget, Constant, Op, OpFormatPart, Program, Reg};

/// Emit the specialized-bodies module for `program`. `vm` is the path the
/// generated module uses to reach the vm crate's `bc` module — `"mimas::vm"`
/// under the `mimas` facade, `"vm"` for a direct `mimas-vm` dep.
pub fn emit(program: &Program, vm: &str) -> String {
    let mut w = String::new();
    // `//` rather than `//!` so the file can also live inside `include!`d
    // module blocks, where inner doc comments are rejected.
    let _ = writeln!(
        w,
        "// Generated by mimas-bcgen — chunk-specialized `step_one` bodies for one\n\
         // fixed program. Do not edit; regenerate from the source instead.\n\
         // Ops without a specialization below call `step`, the interpreter's own\n\
         // dispatch, so coverage is always total.\n\
         // (inner `#![allow]`s aren't permitted inside `include!`, so the\n\
         // allows live on the items themselves.)\n\
         #[allow(unused_imports)]\n\
         use {vm}::bc::*;\n"
    );
    for (body, _) in program.chunks.iter() {
        emit_body(&mut w, program, body.index());
    }
    // Complete table for in-body dynamic `Call` dispatch; `CallDirect` bypasses
    // it and names `body_N` directly. These are the *inner* Rust fns — the
    // driver-facing `BodyFn` ABI goes through the `body_N_abi` wrappers.
    let _ = writeln!(
        w,
        "\n#[allow(dead_code)]\nstatic BODIES: &[InnerBodyFn] = &[{}];",
        (0..program.chunks.len())
            .map(|i| format!("body_{i}"))
            .collect::<Vec<_>>()
            .join(", ")
    );
    let _ = writeln!(
        w,
        "\n/// The install table for `Vm::install_bc`, indexed by `BodyId` — the\n\
         /// extern-\"C\" ABI wrappers, so the same table shape also accepts\n\
         /// Cranelift-JIT bodies.\n\
         pub fn bodies() -> Vec<Option<BodyFn>> {{"
    );
    let _ = writeln!(w, "    vec![");
    for (body, _) in program.chunks.iter() {
        let _ = writeln!(w, "        Some(body_{}_abi),", body.index());
    }
    let _ = writeln!(w, "    ]");
    let _ = writeln!(w, "}}");
    w
}

/// What scalar kind a writer produces for its destination register.
#[derive(Clone, Copy, PartialEq)]
enum W {
    Int,
    Float,
    /// The written value copies another register — inherits its class.
    Copy(u32),
    /// Anything else: the register isn't eligible for a scalar shadow.
    Dyn,
}

/// Registers safe to shadow as native scalars for one body.
///
/// A register joins `int` when *every* op that can write it provably produces
/// `Val::Int` — including vacuous membership (parameters and other never-written
/// registers, whose entry value is checked once at body entry). `Copy(src)`
/// writers adopt `src`'s class, so membership resolves by fixpoint.
struct Sh {
    int: HashSet<u32>,
    float: HashSet<u32>,
}

impl Sh {
    /// The shadow local's name if `r` is int-shadowed.
    fn int(&self, r: Reg) -> Option<String> {
        self.int
            .contains(&(r.index() as u32))
            .then(|| format!("r{}i", r.index()))
    }
    fn float(&self, r: Reg) -> Option<String> {
        self.float
            .contains(&(r.index() as u32))
            .then(|| format!("r{}f", r.index()))
    }
    /// Read `r` as a `Val` — from the live shadow (regs may lag under deferred
    /// writeback), else the authoritative slot. Emitted parenthesized so it's
    /// safe in any operand position.
    fn rdv(&self, r: Reg) -> String {
        let i = r.index();
        if let Some(v) = self.int(r) {
            format!(
                "(if r{i}ok {{ Val::Int({v}) }} else {{ rd(regs, {}) }})",
                reg(r)
            )
        } else if let Some(v) = self.float(r) {
            format!(
                "(if r{i}ok {{ Val::Float({v}) }} else {{ rd(regs, {}) }})",
                reg(r)
            )
        } else {
            format!("rd(regs, {})", reg(r))
        }
    }

    /// Scalar-write under deferred writeback: `valexpr` is a bare `i64`/`f64`.
    /// A shadowed register updates only the local + flag — `regs` is synced
    /// lazily by `flush!()` at body exits and call boundaries; an unshadowed
    /// register writes the tagged `Val` through as before.
    fn wr_shadow(&self, s: &mut String, r: Reg, kind: &str, valexpr: &str) {
        if let Some(v) = self.int(r) {
            let _ = writeln!(s, "{v} = {valexpr}; r{idx}ok = true;", idx = r.index());
        } else if let Some(v) = self.float(r) {
            let _ = writeln!(s, "{v} = {valexpr}; r{idx}ok = true;", idx = r.index());
        } else {
            let _ = writeln!(s, "wr(regs, {}, Val::{kind}({valexpr}));", reg(r));
        }
    }

    /// Generic `Val` write into `r`, keeping the shadow + flag in sync. Only
    /// needed for dsts `analyze` might still shadow (a `Copy` chain); every
    /// `Dyn`-classified writer is unshadowed and compiles to a plain `wr`.
    fn wr_val(&self, s: &mut String, r: Reg, valexpr: &str) {
        if self.int(r).is_some() {
            let _ = writeln!(
                s,
                "match ({valexpr}) {{ Val::Int(x) => {{ r{i}i = x; r{i}ok = true; }}, v => {{ r{i}ok = false; wr(regs, {}, v) }} }};",
                reg(r),
                i = r.index()
            );
        } else if self.float(r).is_some() {
            let _ = writeln!(
                s,
                "match ({valexpr}) {{ Val::Float(x) => {{ r{i}f = x; r{i}ok = true; }}, v => {{ r{i}ok = false; wr(regs, {}, v) }} }};",
                reg(r),
                i = r.index()
            );
        } else {
            let _ = writeln!(s, "wr(regs, {}, ({valexpr}));", reg(r));
        }
    }

    /// The `flush!()` macro body: write every live shadow back to `regs`, the
    /// authoritative frame any observer (interpreter fallback, callee frames'
    /// snapshots, the host between batches) can read.
    fn flush(&self, s: &mut String) {
        for &r in &self.int {
            let _ = writeln!(
                s,
                "if r{r}ok {{ wr(regs, Reg::from({r}u32), Val::Int(r{r}i)); }}"
            );
        }
        for &r in &self.float {
            let _ = writeln!(
                s,
                "if r{r}ok {{ wr(regs, Reg::from({r}u32), Val::Float(r{r}f)); }}"
            );
        }
    }
}

/// Register-write classes for one body — every `dst` (plus `ForNext`'s `idx`,
/// which ForNext itself increments) the body's ops can store to, and which
/// registers occupy int/float-typed operand positions (typed reads).
fn analyze(ops: &[(usize, Op)], nregs: u32) -> Sh {
    let mut writes: HashMap<u32, Vec<W>> = HashMap::new();
    let mut put = |r: Reg, w: W| writes.entry(r.index() as u32).or_default().push(w);
    let mut int_reads: HashSet<u32> = HashSet::new();
    let mut float_reads: HashSet<u32> = HashSet::new();
    let mut iread = |r: Reg| {
        int_reads.insert(r.index() as u32);
    };
    let mut fread = |r: Reg| {
        float_reads.insert(r.index() as u32);
    };
    for (_, op) in ops {
        match op {
            Op::Move { dst, src } => put(*dst, W::Copy(src.index() as u32)),
            Op::LoadConst { dst, constant } => put(
                *dst,
                match constant {
                    Constant::Int(_) => W::Int,
                    Constant::Float(_) => W::Float,
                    _ => W::Dyn,
                },
            ),
            Op::AddInt { dst, left, right }
            | Op::SubInt { dst, left, right }
            | Op::MultInt { dst, left, right }
            | Op::ModInt { dst, left, right }
            | Op::IntLt { dst, left, right }
            | Op::IntLe { dst, left, right }
            | Op::IntGt { dst, left, right }
            | Op::IntGe { dst, left, right }
            | Op::IntEq { dst, left, right }
            | Op::IntNe { dst, left, right } => {
                iread(*left);
                iread(*right);
                put(
                    *dst,
                    if matches!(
                        op,
                        Op::AddInt { .. }
                            | Op::SubInt { .. }
                            | Op::MultInt { .. }
                            | Op::ModInt { .. }
                    ) {
                        W::Int
                    } else {
                        W::Dyn
                    },
                );
            }
            Op::AddIntImm { dst, left, .. }
            | Op::SubIntImm { dst, left, .. }
            | Op::MultIntImm { dst, left, .. }
            | Op::ModIntImm { dst, left, .. } => {
                iread(*left);
                put(*dst, W::Int);
            }
            Op::IntLtImm { dst, left, .. }
            | Op::IntLeImm { dst, left, .. }
            | Op::IntGtImm { dst, left, .. }
            | Op::IntGeImm { dst, left, .. }
            | Op::IntEqImm { dst, left, .. }
            | Op::IntNeImm { dst, left, .. } => {
                iread(*left);
                put(*dst, W::Dyn);
            }
            Op::AddFloat { dst, left, right }
            | Op::SubFloat { dst, left, right }
            | Op::MultFloat { dst, left, right }
            | Op::DivFloat { dst, left, right } => {
                fread(*left);
                fread(*right);
                put(*dst, W::Float);
            }
            Op::FloatLt { dst, left, right }
            | Op::FloatLe { dst, left, right }
            | Op::FloatGt { dst, left, right }
            | Op::FloatGe { dst, left, right }
            | Op::FloatEq { dst, left, right }
            | Op::FloatNe { dst, left, right } => {
                fread(*left);
                fread(*right);
                put(*dst, W::Dyn);
            }
            Op::AddFloatImm { dst, left, .. }
            | Op::SubFloatImm { dst, left, .. }
            | Op::MultFloatImm { dst, left, .. }
            | Op::ModFloatImm { dst, left, .. } => {
                fread(*left);
                put(*dst, W::Float);
            }
            Op::FloatLtImm { dst, left, .. }
            | Op::FloatLeImm { dst, left, .. }
            | Op::FloatGtImm { dst, left, .. }
            | Op::FloatGeImm { dst, left, .. }
            | Op::FloatEqImm { dst, left, .. }
            | Op::FloatNeImm { dst, left, .. } => {
                fread(*left);
                put(*dst, W::Dyn);
            }
            Op::Len { dst, .. } => put(*dst, W::Int),
            Op::ToFloat { dst, src } => {
                iread(*src);
                put(*dst, W::Float);
            }
            Op::Sqrt { dst, src } => {
                fread(*src);
                put(*dst, W::Float);
            }
            Op::ForNext { idx, bound, .. } => {
                iread(*idx);
                iread(*bound);
                put(*idx, W::Int);
            }
            Op::BIntLt { left, right, .. }
            | Op::BIntLe { left, right, .. }
            | Op::BIntGt { left, right, .. }
            | Op::BIntGe { left, right, .. }
            | Op::BIntEq { left, right, .. }
            | Op::BIntNe { left, right, .. } => {
                iread(*left);
                iread(*right);
            }
            Op::BIntLtImm { left, .. }
            | Op::BIntLeImm { left, .. }
            | Op::BIntGtImm { left, .. }
            | Op::BIntGeImm { left, .. }
            | Op::BIntEqImm { left, .. }
            | Op::BIntNeImm { left, .. } => iread(*left),
            Op::BFloatLt { left, right, .. }
            | Op::BFloatLe { left, right, .. }
            | Op::BFloatGt { left, right, .. }
            | Op::BFloatGe { left, right, .. }
            | Op::BFloatEq { left, right, .. }
            | Op::BFloatNe { left, right, .. } => {
                fread(*left);
                fread(*right);
            }
            Op::BFloatLtImm { left, .. }
            | Op::BFloatLeImm { left, .. }
            | Op::BFloatGtImm { left, .. }
            | Op::BFloatGeImm { left, .. }
            | Op::BFloatEqImm { left, .. }
            | Op::BFloatNeImm { left, .. } => fread(*left),
            // every other op that carries a dst writes a dynamically-typed
            // value (bools, strings, calls, collections, ...)
            Op::GetField { dst, .. }
            | Op::GetIndex { dst, .. }
            | Op::LoadBody { dst, .. }
            | Op::LoadEntry { dst, .. }
            | Op::BoolEq { dst, .. }
            | Op::BoolNe { dst, .. }
            | Op::StrEq { dst, .. }
            | Op::StrNe { dst, .. }
            | Op::Bin { dst, .. }
            | Op::Unary { dst, .. }
            | Op::In { dst, .. }
            | Op::IsInstance { dst, .. }
            | Op::IsRaised { dst, .. }
            | Op::UnwrapRaised { dst, .. }
            | Op::Unwrap { dst, .. }
            | Op::UnwrapUnit { dst, .. }
            | Op::NewArray { dst }
            | Op::NewDict { dst }
            | Op::NewInstance { dst, .. }
            | Op::NewClosure { dst, .. }
            | Op::Format { dst, .. }
            | Op::Call { dst, .. }
            | Op::CallDirect { dst, .. }
            | Op::CallNative { dst, .. } => put(*dst, W::Dyn),
            // no register destination
            Op::Jump { .. }
            | Op::JumpIf { .. }
            | Op::Switch { .. }
            | Op::Push { .. }
            | Op::Insert { .. }
            | Op::SetIndex { .. }
            | Op::SetField { .. }
            | Op::StoreEntry { .. }
            | Op::Return { .. }
            | Op::Panic {}
            | Op::Raise { .. } => {}
        }
    }

    let mut int: HashSet<u32> = HashSet::new();
    let mut float: HashSet<u32> = HashSet::new();
    // Phase 1: never-written registers (params, scratch) — the only writers
    // can't pin a class, so the *reads* decide. An unwritten reg shadowed as
    // int that actually holds a float at runtime bails to `step` at body
    // entry, so at most one of the two sets claims it.
    for r in 0..nregs {
        if writes.contains_key(&r) {
            continue;
        }
        match (int_reads.contains(&r), float_reads.contains(&r)) {
            (true, false) => {
                int.insert(r);
            }
            (false, true) => {
                float.insert(r);
            }
            _ => {}
        }
    }
    // Phase 2 fixpoint: a written reg shadows as int iff every writer produces
    // Int or Copies an int-set member (likewise float).
    loop {
        let mut changed = false;
        for (&r, ws) in &writes {
            let ok_i = ws.iter().all(|w| match w {
                W::Int => true,
                W::Copy(src) => int.contains(src),
                _ => false,
            });
            let ok_f = ws.iter().all(|w| match w {
                W::Float => true,
                W::Copy(src) => float.contains(src),
                _ => false,
            });
            if ok_i != int.contains(&r) {
                if ok_i {
                    int.insert(r);
                } else {
                    int.remove(&r);
                }
                changed = true;
            }
            if ok_f != float.contains(&r) {
                if ok_f {
                    float.insert(r);
                } else {
                    float.remove(&r);
                }
                changed = true;
            }
        }
        if !changed {
            break;
        }
    }
    Sh { int, float }
}

fn emit_body(w: &mut String, program: &Program, body: usize) {
    let body_id = compile::BodyId::from(body as u32);
    let ops = program.ops(body_id);
    let sh = analyze(&ops, program.chunks[body_id].regs as u32);
    let _ = writeln!(
        w,
        "\n#[allow(unused_variables, unused_mut, unused_assignments, unused_comparisons, unused_parens, unused_macros, clippy::all)]\n\
         fn body_{body}<'gc>(\n\
         \x20   thread: &mut ThreadState<'gc>,\n\
         \x20   code: &mut Decoder,\n\
         \x20   ctx: Ctx<'gc>,\n\
         \x20   strs: &StrInterner,\n\
         \x20   chunks: &IdVec<BodyId, Chunk>,\n\
         \x20   signatures: &IdVec<BodyId, Option<Function>>,\n\
         \x20   fuel: &mut usize,\n\
         \x20   op_ip: &mut usize,\n\
         ) -> RtResult<Flow<'gc>> {{"
    );
    let _ = writeln!(
        w,
        "    let base = thread.frames.last().unwrap().base;\n\
         \x20   let nregs = chunks[thread.frames.last().unwrap().chunk].regs as usize;\n\
         \x20   // the same raw-window idiom as `run_dispatch`'s `window()`: `regs` may\n\
         \x20   // dangle after any `thread.regs` resize/truncate (inline `enter_call`,\n\
         \x20   // a callee's return pop) — always rebuild it before the next use.\n\
         \x20   let mut regs = unsafe {{\n\
         \x20       std::slice::from_raw_parts_mut(thread.regs.as_mut_ptr().add(base), nregs)\n\
         \x20   }};"
    );
    // Shadowed registers are initialized once per invocation, straight from
    // `regs` — which is authoritative even mid-body thanks to write-through.
    // Each shadow carries an `ok` flag: a non-matching entry value (mistyped
    // call arg, uninitialized slot) just leaves the flag false and reads take
    // the op's own cold path — exactly what the interpreter's tag-miss does.
    for &r in &sh.int {
        let _ = writeln!(
            w,
            "    let (mut r{r}i, mut r{r}ok) = match rd(regs, Reg::from({r}u32)) {{\n\
             \x20       Val::Int(v) => (v, true),\n\
             \x20       _ => (0i64, false),\n\
             \x20   }};"
        );
    }
    for &r in &sh.float {
        let _ = writeln!(
            w,
            "    let (mut r{r}f, mut r{r}ok) = match rd(regs, Reg::from({r}u32)) {{\n\
             \x20       Val::Float(v) => (v, true),\n\
             \x20       _ => (0.0f64, false),\n\
             \x20   }};"
        );
    }
    // Deferred writeback: scalar writes go to the shadow locals only, and
    // `flush!()` writes live shadows back to `regs` at every boundary where
    // anything else can observe the frame — body exits (pause/fuel/error/
    // interpreter fallback/`Flow::Call`), and just before an inlined
    // `enter_call`. `return`s inside op arms get the flush from `defer`.
    let _ = writeln!(w, "    macro_rules! flush {{ () => {{");
    let mut flush_body = String::new();
    sh.flush(&mut flush_body);
    w.push_str(&flush_body);
    let _ = writeln!(w, "    }}}}");
    // Per-op bookkeeping is the driver's, batched: `bcn` counts down a local
    // quota of `min(fuel, ops_left)` — both are consumed strictly per op and
    // can't be touched mid-body (natives never see `fuel`, and `thread` is
    // borrow_mut-held), so `*fuel`/`thread.ops_left` are only synced by
    // `settle!()` at body exits and re-armed after an inlined call consumed
    // some. `bcn0` remembers `bcn` at the last settle so `spent` is exact.
    // When `bcn` hits 0 the ordered exit reasons reproduce run_dispatch's:
    // paused or `fuel == 0` → `Flow::Next`, `ops_left == 0` → `OutOfFuel`
    // (paused first, matching the driver's own ordering).
    let _ = writeln!(w, "    let mut bcn: u64 = (*fuel as u64).min(thread.ops_left);");
    let _ = writeln!(w, "    let mut bcn0: u64 = bcn;");
    let _ = writeln!(
        w,
        "    macro_rules! settle {{ () => {{{{\n\
         \x20       let spent = bcn0 - bcn; bcn0 = bcn;\n\
         \x20       *fuel -= spent as usize;\n\
         \x20       thread.ops_left -= spent;\n\
         \x20   }}}}}}\n\
         \x20   macro_rules! gexit {{ () => {{{{\n\
         \x20       settle!();\n\
         \x20       if ctx.state().paused.get() | (*fuel == 0) {{ flush!(); return Ok(Flow::Next); }}\n\
         \x20       if thread.ops_left == 0 {{ *op_ip = code.ip; flush!(); return Err(RtErr::OutOfFuel); }}\n\
         \x20       bcn = (*fuel as u64).min(thread.ops_left); bcn0 = bcn;\n\
         \x20   }}}}}}\n\
         \x20   macro_rules! gateq {{ () => {{{{\n\
         \x20       if bcn == 0 {{ gexit!(); }}\n\
         \x20       bcn -= 1;\n\
         \x20   }}}}}}\n\
         \x20   macro_rules! gatep {{ () => {{{{\n\
         \x20       if ctx.state().paused.get() | (bcn == 0) {{ gexit!(); }}\n\
         \x20       bcn -= 1;\n\
         \x20   }}}}}}\n\
         \x20   macro_rules! pchk {{ () => {{{{\n\
         \x20       if ctx.state().paused.get() {{ settle!(); flush!(); return Ok(Flow::Next); }}\n\
         \x20   }}}}}}"
    );
    let _ = writeln!(w, "    loop {{");
    let _ = writeln!(w, "        match code.ip {{");
    let n_ops = ops.len();
    let off_idx: HashMap<usize, usize> = ops
        .iter()
        .enumerate()
        .map(|(i, (o, _))| (*o, i))
        .collect();
    let mut is_tgt = vec![false; n_ops];
    for (_, op) in &ops {
        for t in edge_targets(op) {
            if let Some(&j) = off_idx.get(&t) {
                is_tgt[j] = true;
            }
        }
    }
    // Calls are never inlined into a chain: they always lead (or stand as)
    // their own arm. Besides being the fattest emitted code (doubling it
    // would bloat the body's stack frame — visible in debug builds where
    // the inline-call recursion is deepest), a mid-chain `Flow::Call`
    // resume lands on `next` anyway, which already re-dispatches.
    let is_call = |op: &Op| {
        matches!(
            op,
            Op::Call { .. } | Op::CallDirect { .. } | Op::CallNative { .. }
        )
    };
    // A "leader" is an arm whose fallthrough chain gets inlined into it —
    // chunk entry, a branch target, or the op right after a terminator.
    // Non-leader arms stay single-op stubs; they're only reached on resume
    // after a pause/fuel/call return mid-block.
    let leader =
        |i: usize| i == 0 || is_tgt[i] || !fallthrough(&ops[i - 1].1) || is_call(&ops[i].1);
    // The last op index of the fallthrough chain starting at `i`.
    let chain_end = |mut i: usize| {
        while i + 1 < n_ops && fallthrough(&ops[i].1) && !is_call(&ops[i + 1].1) {
            i += 1;
        }
        i
    };
    let tail_norm = |t: usize| format!("code.ip = {t};");
    for i in 0..n_ops {
        let head = ops[i].0;
        let seq: Vec<usize> = if leader(i) {
            (i..=chain_end(i)).collect()
        } else {
            vec![i]
        };
        let term = *seq.last().unwrap();
        // Loop-wrap: if the block's terminator can branch back to `head`,
        // emit the whole arm as a Rust `loop` so the back-edge is a direct
        // `continue` — no `match` re-dispatch. Also covers the `while`
        // shape: head block ends in a conditional whose taken target is a
        // block that jumps back to `head`.
        let mut extra: Vec<usize> = vec![];
        let mut fall_t = usize::MAX; // a taken edge of `term` that falls into `extra`
        let mut wrap = !matches!(ops[term].1, Op::Switch { .. })
            && edge_targets(&ops[term].1).contains(&head);
        if !wrap && let Some(tk) = cond_target(&ops[term].1) {
            if let Some(&m) = off_idx.get(&tk)
                && m > term
                && !matches!(ops[chain_end(m)].1, Op::Switch { .. })
                && edge_targets(&ops[chain_end(m)].1).contains(&head)
            {
                wrap = true;
                extra = (m..=chain_end(m)).collect();
                fall_t = tk;
            }
        }
        // Emits one run of ops (`seq`, then `extra`): `gates` toggles the
        // per-op `gateq!()`/`gatep!()` bookkeeping; when off (the fast path),
        // `restock` is the whole region's op count and the exit paths hand
        // back the ops that never ran — `bcn` was pre-paid `bcn -= len`, so
        // an op at region position `pos0 + k` restocks `len-1-(pos0+k)`
        // before `settle!()` computes `spent`. Keeps the interpreter's
        // decrement-before-run accounting exact on error/bail exits.
        let emit_ops = |w: &mut String,
                        idxs: &[usize],
                        gates: bool,
                        restock: usize,
                        pos0: usize,
                        term_tail: &dyn Fn(usize) -> String| {
            if idxs.is_empty() {
                return;
            }
            let last = *idxs.last().unwrap();
            for (k, &j) in idxs.iter().enumerate() {
                let (off, op) = &ops[j];
                let next = ops.get(j + 1).map(|(o, _)| *o).unwrap_or(usize::MAX);
                if gates {
                    w.push_str(if j > 0 && may_pause(&ops[j - 1].1) {
                        "            gatep!();\n"
                    } else {
                        "            gateq!();\n"
                    });
                }
                let mut arm = String::new();
                let t: &dyn Fn(usize) -> String = if j == last {
                    term_tail
                } else {
                    &tail_norm
                };
                emit_op(&mut arm, &sh, *off, next, op, t);
                w.push_str(&defer(&arm, &sh, if gates {
                    0
                } else {
                    (restock - 1 - (pos0 + k)) as u64
                }));
            }
        };
        if wrap {
            let region: Vec<usize> = seq.iter().chain(extra.iter()).copied().collect();
            let pure = region.iter().all(|&j| !may_pause(&ops[j].1));
            let blen = region.len();
            // terminator tails: an edge to `head` is `continue`, `term`'s
            // `fall_t` edge falls into the inlined `extra` block, anything
            // else exits the loop and re-dispatches on `code.ip`.
            let tail_head = |t: usize| {
                if t == fall_t {
                    String::new()
                } else if t == head {
                    "continue;".to_string()
                } else {
                    format!("code.ip = {t}; break;")
                }
            };
            // Same shape for the pre-paid fast path, except an exit edge at
            // `term` skips the whole `extra` block — hand those ops back or
            // the counters would charge for ops that never ran.
            let tail_head_fast = |t: usize| {
                if t == fall_t {
                    String::new()
                } else if t == head {
                    "continue;".to_string()
                } else if extra.is_empty() {
                    format!("code.ip = {t}; break;")
                } else {
                    format!("code.ip = {t}; bcn += {}u64; break;", extra.len())
                }
            };
            let tail_loop = |t: usize| {
                if t == head {
                    "continue;".to_string()
                } else {
                    format!("code.ip = {t}; break;")
                }
            };
            let _ = writeln!(w, "            {head} => {{");
            // `paused` can't change inside a pure region — one entry check
            // covers the whole loop when the fallthrough predecessor could
            // have set it (the flag is then unset for every iteration).
            if pure && i > 0 && may_pause(&ops[i - 1].1) {
                let _ = writeln!(w, "            pchk!();");
            }
            let _ = writeln!(w, "            loop {{");
            // `code.ip` must sit at `head` on every iteration: the head op's
            // own `step`-bails and the gates' `*op_ip`/Flow::Next save slot
            // all read it.
            let _ = writeln!(w, "            code.ip = {head};");
            if pure {
                let _ = writeln!(
                    w,
                    "            if bcn >= {blen}u64 {{ bcn -= {blen}u64;"
                );
                emit_ops(w, &seq, false, blen, 0, &tail_head_fast);
                emit_ops(w, &extra, false, blen, seq.len(), &tail_loop);
                let _ = writeln!(w, "            }} else {{");
                emit_ops(w, &seq, true, blen, 0, &tail_head);
                emit_ops(w, &extra, true, blen, seq.len(), &tail_loop);
                let _ = writeln!(w, "            }}");
            } else {
                emit_ops(w, &seq, true, blen, 0, &tail_head);
                emit_ops(w, &extra, true, blen, seq.len(), &tail_loop);
            }
            let _ = writeln!(w, "            }}");
            let _ = writeln!(w, "            }}");
        } else {
            let _ = writeln!(w, "            {head} => {{");
            emit_ops(w, &seq, true, 0, 0, &tail_norm);
            let _ = writeln!(w, "            }}");
        }
    }
    // an ip outside the chunk's op stream can only come from a codegen bug --
    // hand it to the interpreter, which hits the same garbage decode either way
    let _ = writeln!(
        w,
        "            _ => {{ *op_ip = code.ip; gatep!(); settle!(); flush!(); return step(regs, code, ctx, strs, &thread.frames); }}"
    );
    let _ = writeln!(w, "        }}");
    let _ = writeln!(w, "    }}");
    let _ = writeln!(w, "}}");
    // The driver-facing ABI shim: `BodyFn` is `extern "C"` with the result
    // routed through `out` so Cranelift-JIT bodies install interchangeably.
    // In-module calls (the inline-call fast path, `BODIES`) use the inner
    // `body_N` directly and never pay this hop.
    let _ = writeln!(
        w,
        "\n#[allow(clippy::all)]\n\
         unsafe extern \"C\" fn body_{body}_abi<'gc>(\n\
         \x20   thread: *mut ThreadState<'gc>,\n\
         \x20   code: *mut Decoder,\n\
         \x20   ctx: Ctx<'gc>,\n\
         \x20   strs: *const StrInterner,\n\
         \x20   chunks: *const IdVec<BodyId, Chunk>,\n\
         \x20   signatures: *const IdVec<BodyId, Option<Function>>,\n\
         \x20   fuel: *mut usize,\n\
         \x20   op_ip: *mut usize,\n\
         \x20   out: *mut RtResult<Flow<'gc>>,\n\
         ) {{\n\
         \x20   // SAFETY: the BodyFn contract — pointers borrow live driver\n\
         \x20   // state for the call's duration; `out` is a live slot.\n\
         \x20   unsafe {{\n\
         \x20       *out = body_{body}(\n\
         \x20           &mut *thread, &mut *code, ctx, &*strs, &*chunks, &*signatures,\n\
         \x20           &mut *fuel, &mut *op_ip,\n\
         \x20       );\n\
         \x20   }}\n\
         }}"
    );
}

/// The interpreter checks `State::paused` before every op, but the flag can
/// only change inside an op that runs foreign code — `bin`/`unary` can reach
/// registered instance-op impls, and `Call*`/`CallNative` run natives and
/// callee bodies (whose own gates propagate a pause as `Flow::Next`). Every
/// other op is pure register/Rust work, so `paused` only needs checking on
/// the op *after* one of these — and inline callees return `Flow::Return`
/// only when their last gate saw the flag clear.
fn may_pause(op: &Op) -> bool {
    matches!(
        op,
        Op::Bin { .. }
            | Op::Unary { .. }
            | Op::Call { .. }
            | Op::CallDirect { .. }
            | Op::CallNative { .. }
    )
}

/// Falls through to the next op on the success path — every other way out is
/// a `return`. Terminators (branches, switches, exits) have no fallthrough.
fn fallthrough(op: &Op) -> bool {
    !matches!(
        op,
        Op::Jump { .. }
            | Op::JumpIf { .. }
            | Op::Switch { .. }
            | Op::ForNext { .. }
            | Op::BIntLt { .. }
            | Op::BIntLe { .. }
            | Op::BIntGt { .. }
            | Op::BIntGe { .. }
            | Op::BIntEq { .. }
            | Op::BIntNe { .. }
            | Op::BIntLtImm { .. }
            | Op::BIntLeImm { .. }
            | Op::BIntGtImm { .. }
            | Op::BIntGeImm { .. }
            | Op::BIntEqImm { .. }
            | Op::BIntNeImm { .. }
            | Op::BFloatLt { .. }
            | Op::BFloatLe { .. }
            | Op::BFloatGt { .. }
            | Op::BFloatGe { .. }
            | Op::BFloatEq { .. }
            | Op::BFloatNe { .. }
            | Op::BFloatLtImm { .. }
            | Op::BFloatLeImm { .. }
            | Op::BFloatGtImm { .. }
            | Op::BFloatGeImm { .. }
            | Op::BFloatEqImm { .. }
            | Op::BFloatNeImm { .. }
            | Op::Return { .. }
            | Op::Raise { .. }
            | Op::Panic {}
    )
}

/// Every successor `op` may jump to, as byte offsets — the `next` fallthrough
/// edge is implicit, so only branch/switch targets are listed.
fn edge_targets(op: &Op) -> Vec<usize> {
    let t = |target: &BlockTarget| tgt(target);
    match op {
        Op::Jump { target } | Op::JumpIf { target, .. } | Op::ForNext { target, .. } => {
            vec![t(target)]
        }
        Op::Switch {
            table, default, ..
        } => table.iter().map(t).chain(std::iter::once(t(default))).collect(),
        Op::BIntLt { target, .. }
        | Op::BIntLe { target, .. }
        | Op::BIntGt { target, .. }
        | Op::BIntGe { target, .. }
        | Op::BIntEq { target, .. }
        | Op::BIntNe { target, .. }
        | Op::BIntLtImm { target, .. }
        | Op::BIntLeImm { target, .. }
        | Op::BIntGtImm { target, .. }
        | Op::BIntGeImm { target, .. }
        | Op::BIntEqImm { target, .. }
        | Op::BIntNeImm { target, .. }
        | Op::BFloatLt { target, .. }
        | Op::BFloatLe { target, .. }
        | Op::BFloatGt { target, .. }
        | Op::BFloatGe { target, .. }
        | Op::BFloatEq { target, .. }
        | Op::BFloatNe { target, .. }
        | Op::BFloatLtImm { target, .. }
        | Op::BFloatLeImm { target, .. }
        | Op::BFloatGtImm { target, .. }
        | Op::BFloatGeImm { target, .. }
        | Op::BFloatEqImm { target, .. }
        | Op::BFloatNeImm { target, .. } => vec![t(target)],
        _ => vec![],
    }
}

/// The taken edge of a two-edge conditional terminator — `None` for
/// unconditional (Jump), multi-edge (Switch), or non-branching ops.
fn cond_target(op: &Op) -> Option<usize> {
    edge_targets(op).into_iter().next().filter(|_| {
        !matches!(op, Op::Jump { .. } | Op::Switch { .. })
    })
}

/// Post-processes one emitted op arm for deferred writeback:
/// - every `return` first runs `flush!()`, restoring `regs` as the authoritative frame for whatever
///   observes it next (the driver, an inlined callee's snapshot, the interpreter's cold dispatch);
/// - every `rd(regs, Reg::from(Nu32))` on a shadowed register becomes a shadow-aware read — with
///   write-through gone, `regs` there can be stale.
fn defer(arm: &str, sh: &Sh, restock: u64) -> String {
    // `restock` > 0 means the op ran under a pre-paid fast path (`bcn -= len`
    // covered the whole region): returns hand back the ops that never ran so
    // `settle!()` charges exactly the ones that did.
    let mut out = arm.replace(
        "return ",
        &format!("bcn += {restock}u64; settle!(); flush!(); return "),
    );
    if restock == 0 {
        out = out.replace("bcn += 0u64; ", "");
    }
    // ...then reclaim the pointless ones. A `Flow::Return` destroys the
    // frame — nothing observes its regs — except the root frame, which the
    // host inspects after `run()`. The call fast-path's propagations are
    // already flushed pre-`enter_call`.
    out = out.replace(
        "flush!(); return Ok(Flow::Return",
        "if thread.frames.len() == 1 { flush!(); } return Ok(Flow::Return",
    );
    out = out.replace("flush!(); return res }", "return res }");
    out = out.replace("flush!(); return Err(kind) }", "return Err(kind) }");
    for &r in &sh.int {
        let plain = format!("rd(regs, Reg::from({r}u32))");
        out = out.replace(
            &plain,
            &format!("(if r{r}ok {{ Val::Int(r{r}i) }} else {{ {plain} }})"),
        );
    }
    for &r in &sh.float {
        let plain = format!("rd(regs, Reg::from({r}u32))");
        out = out.replace(
            &plain,
            &format!("(if r{r}ok {{ Val::Float(r{r}f) }} else {{ {plain} }})"),
        );
    }
    out
}

fn reg(r: Reg) -> String {
    format!("Reg::from({}u32)", r.index())
}

fn tgt(t: &BlockTarget) -> usize {
    let BlockTarget::ByteOffset(o) = t else {
        panic!("unresolved BlockTarget in compiled program")
    };
    *o
}

/// The in-body call path: enter the callee frame ourselves (verbatim
/// `enter_call`), recurse into its specialized body, and on `Flow::Return`
/// run the driver's pop/`dst`-write/`ip`-restore — all without a driver
/// round-trip. `Flow::Next`/`Err`/a `Flow::Call` from deeper (a callee at the
/// cap) propagate unchanged: the frames are exactly as the driver would see
/// them had it dispatched the callee itself. Depth at/over
/// `INLINE_CALL_DEPTH` falls back to `Flow::Call` — `code.ip` is already at
/// `next` (emitted before this) so the driver's enter_call saves the right
/// resume slot.
fn emit_call_fast(
    s: &mut String,
    dst: Reg,
    callee: &str,
    captures: &str,
    target: &str,
    arg_regs: &[Reg],
    sh: &Sh,
) {
    // `settle!()` before entering the callee: it draws fuel/ops_left from the
    // same counters our `bcn` was armed against, so our spent ops must be
    // charged first or the propagate-path `settle!()` would subtract them
    // twice (debug underflow). Natives can't observe this — `thread` stays
    // `borrow_mut`-held for the whole dispatch.
    let regs_list = arg_regs
        .iter()
        .map(|r| format!("Reg::from({}u32)", r.index()))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(
        s,
        "if thread.frames.len() < INLINE_CALL_DEPTH {{
            settle!();
            flush!();
            match enter_call_regs(thread, code, chunks, {callee}, {}, &[{regs_list}], {captures}) {{
                Ok(()) => {{
                    let res = {f}(thread, code, ctx, strs, chunks, signatures, fuel, op_ip);
                    // the callee's `enter_call` may have moved `thread.regs` —
                    // rebuild the caller window before anything touches it
                    // (`flush!()` on the propagate paths included)
                    regs = unsafe {{
                        std::slice::from_raw_parts_mut(thread.regs.as_mut_ptr().add(base), nregs)
                    }};
                    match res {{
                        Ok(Flow::Return(v)) => {{
                            let popped = thread.frames.pop().unwrap();
                            thread.regs.truncate(popped.base);
                            let caller = thread.frames.last().unwrap();
                            code.ip = caller.ip;
                            let caller_base = caller.base;
                            thread.regs[caller_base + popped.return_reg as usize] = v;
                            regs = unsafe {{
                                std::slice::from_raw_parts_mut(thread.regs.as_mut_ptr().add(base), nregs)
                            }};
                        }}
                        _ => {{ return res }},
                    }}
                    // the callee consumed fuel/ops_left through its own
                    // `bcn` quota — re-arm ours from the settled counters
                    bcn = (*fuel as u64).min(thread.ops_left); bcn0 = bcn;
                }},
                Err(kind) => {{ return Err(kind) }},
            }}
        }}",
        reg(dst),
        f = callee_fn(callee)
    );
    // The at-cap path needs `args` as values for the `Flow::Call` payload —
    // only build the SmallVec there; the inline path read the caller window
    // straight through `enter_call_regs`.
    let _ = writeln!(s, "else {{");
    let _ = writeln!(s, "    let mut args = SmallVec::<[Val; 8]>::new();");
    for a in arg_regs {
        let _ = writeln!(s, "    args.push(rd(regs, {}));", reg(*a));
    }
    let _ = writeln!(
        s,
        "    return Ok(Flow::Call {{ target: {target}, dst: {}, args }});\n}}",
        reg(dst)
    );
    // The callee's return wrote `regs[dst]` through `thread.regs` — a shadowed
    // dst must refresh its local from the (possibly freshly typed) value.
    if let Some(v) = sh.int(dst) {
        let _ = writeln!(
            s,
            "{v} = match regs[{0}] {{ Val::Int(x) => {{ r{0}ok = true; x }}, _ => {{ r{0}ok = false; 0 }} }};",
            dst.index()
        );
    } else if let Some(v) = sh.float(dst) {
        let _ = writeln!(
            s,
            "{v} = match regs[{0}] {{ Val::Float(x) => {{ r{0}ok = true; x }}, _ => {{ r{0}ok = false; 0.0 }} }};",
            dst.index()
        );
    }
}

/// The callee's body fn expression: `CallDirect` knows it statically
/// (`body_N`), `Call` resolves through the module's `BODIES` table.
fn callee_fn(callee: &str) -> String {
    if let Some(i) = callee
        .strip_prefix("BodyId::from(")
        .and_then(|s| s.strip_suffix("u32)"))
        .and_then(|s| s.parse::<usize>().ok())
    {
        format!("body_{i}")
    } else {
        format!("BODIES[{callee}.index()]")
    }
}

fn access_kind(k: compile::AccessKind) -> &'static str {
    match k {
        compile::AccessKind::Direct => "AccessKind::Direct",
        compile::AccessKind::Option => "AccessKind::Option",
    }
}

/// A `Constant` operand as a Rust expression — `constant_to_val(<this>, ctx,
/// strs)` is exactly what the interpreter's `LoadConst` arm runs.
fn konst(c: &Constant) -> String {
    match c {
        Constant::Null => "Constant::Null".to_string(),
        Constant::Bool(b) => format!("Constant::Bool({b})"),
        Constant::Int(i) => format!("Constant::Int({i}i64)"),
        Constant::Float(f) => format!("Constant::Float(f64::from_bits({}u64))", f.to_bits()),
        Constant::Str(id) => format!("Constant::Str(StrId::from({}u32))", id.index()),
        Constant::Array(items) => {
            let items = items.iter().map(konst).collect::<Vec<_>>().join(", ");
            format!("Constant::Array(vec![{items}])")
        }
    }
}

/// An `i64`-producing expression for an int operand: the shadow local when `r`
/// is unboxed, else a `regs` match whose miss arm tail-calls `cold` verbatim.
/// `cold` must be a complete `return ...;` statement.
fn int_opnd(sh: &Sh, r: Reg, next: usize, off: usize, cold: &str) -> String {
    match sh.int(r) {
        // flag-clear means `regs[r]` holds a non-Int right now — take the same
        // cold path the interpreter's tag-miss would
        Some(v) => format!(
            "if r{idx}ok {{ {v} }} else {{ code.ip = {next}; *op_ip = {off}; {cold} }}",
            idx = r.index()
        ),
        None => format!(
            "match rd(regs, {}) {{ Val::Int(x) => x, _ => {{ code.ip = {next}; *op_ip = {off}; {cold} }} }}",
            reg(r)
        ),
    }
}

fn float_opnd(sh: &Sh, r: Reg, next: usize, off: usize, cold: &str) -> String {
    match sh.float(r) {
        Some(v) => format!(
            "if r{idx}ok {{ {v} }} else {{ code.ip = {next}; *op_ip = {off}; {cold} }}",
            idx = r.index()
        ),
        None => format!(
            "match rd(regs, {}) {{ Val::Float(x) => x, _ => {{ code.ip = {next}; *op_ip = {off}; {cold} }} }}",
            reg(r)
        ),
    }
}

/// One `code.ip` arm inside the body's dispatch loop. `next` is the byte offset
/// of the following op — the value `code.ip` would hold after decoding this op,
/// which the specialized body must reproduce by hand since it never decodes.
/// Every `return` that leaves the body with `Err` or `Flow::Call` first stores
/// the op's offset into `*op_ip` for the driver's `locate`.
fn emit_op(
    w: &mut String,
    sh: &Sh,
    offset: usize,
    next: usize,
    op: &Op,
    tail: &dyn Fn(usize) -> String,
) {
    // The cold helpers (`bin_cold`, `branch_cold`) expect `code.ip` past the
    // op's operands — the interpreter's decode already did that for them — so
    // generated code sets it explicitly before tail-calling. `step` instead
    // wants `code.ip` *at* the op: it re-runs decode + arm wholesale.
    let mut s = String::new();
    macro_rules! wln {
        ($($t:tt)*) => {{ let _ = writeln!(s, $($t)*); }};
    }

    match op {
        Op::Move { dst, src } => {
            // Copy(src) in `int` requires src ∈ int too — propagate the flag so
            // a flag-false src poisons dst exactly as the copied non-Int Val
            // would; flag-false means `regs` is authoritative for dst, so write
            // the (authoritative) src slot through
            if let (Some(d), Some(sv)) = (sh.int(*dst), sh.int(*src)) {
                wln!(
                    "{d} = {sv}; r{didx}ok = r{sidx}ok; if !r{didx}ok {{ wr(regs, {}, rd(regs, {})) }} code.ip = {next};",
                    reg(*dst),
                    reg(*src),
                    didx = dst.index(),
                    sidx = src.index()
                );
            } else if let (Some(d), Some(sv)) = (sh.float(*dst), sh.float(*src)) {
                wln!(
                    "{d} = {sv}; r{didx}ok = r{sidx}ok; if !r{didx}ok {{ wr(regs, {}, rd(regs, {})) }} code.ip = {next};",
                    reg(*dst),
                    reg(*src),
                    didx = dst.index(),
                    sidx = src.index()
                );
            } else {
                sh.wr_val(&mut s, *dst, &sh.rdv(*src));
                wln!("code.ip = {next};");
            }
        }
        Op::NewArray { dst } => {
            wln!(
                "wr(regs, {}, Val::Array(ctx.new_array(Vec::new()))); code.ip = {next};",
                reg(*dst)
            )
        }
        Op::NewDict { dst } => {
            wln!(
                "wr(regs, {}, Val::Dict(ctx.new_dict(DictMap::new()))); code.ip = {next};",
                reg(*dst)
            )
        }
        Op::NewInstance { dst, adt, fields } => {
            wln!("let fields = if {} <= INLINE_FIELDS {{", fields.len());
            wln!("    let mut data = [Val::Null; INLINE_FIELDS];");
            for (i, f) in fields.iter().enumerate() {
                wln!("    data[{i}] = rd(regs, {});", reg(*f));
            }
            wln!("    Fields::Inline {{ len: {}u8, data }}", fields.len());
            wln!("}} else {{");
            let fields = fields
                .iter()
                .map(|f| format!("rd(regs, {})", reg(*f)))
                .collect::<Vec<_>>()
                .join(", ");
            wln!("    Fields::Spilled(vec![{fields}])");
            wln!("}};");
            wln!(
                "wr(regs, {}, Val::Instance(ctx.new_instance({}u32, fields))); code.ip = {next};",
                reg(*dst),
                adt.index()
            );
        }
        Op::NewClosure {
            dst,
            body,
            captures,
        } => {
            let captures = captures
                .iter()
                .map(|c| format!("rd(regs, {})", reg(*c)))
                .collect::<Vec<_>>()
                .join(", ");
            wln!(
                "wr(regs, {}, Val::Closure(ctx.new_closure(BodyId::from({}u32), vec![{captures}]))); code.ip = {next};",
                reg(*dst),
                body.index()
            );
        }
        Op::Push { array, value } => {
            wln!("let arr = rd(regs, {}).as_array().unwrap();", reg(*array));
            wln!("let value = rd(regs, {});", reg(*value));
            wln!("arr.0.borrow_mut(&ctx).push(value);");
            wln!("code.ip = {next};");
        }
        Op::Insert { dict, key, value } => {
            wln!("let dict = rd(regs, {}).as_dict().unwrap();", reg(*dict));
            wln!(
                "let key = ctx.intern(strs.get(StrId::from({}u32)));",
                key.index()
            );
            wln!(
                "dict.0.borrow_mut(&ctx).insert(key, rd(regs, {}));",
                reg(*value)
            );
            wln!("code.ip = {next};");
        }
        Op::SetIndex { set, index, value } => {
            wln!("*op_ip = {offset};");
            wln!(
                "if let Err(e) = set_index(ctx, rd(regs, {}), rd(regs, {}), rd(regs, {})) {{ return Err(e) }};",
                reg(*set),
                reg(*index),
                reg(*value)
            );
            wln!("code.ip = {next};");
        }
        Op::GetIndex {
            dst,
            set,
            index,
            kind,
        } => {
            wln!("*op_ip = {offset};");
            wln!(
                "let v = match get_index(ctx, rd(regs, {}), rd(regs, {}), {}) {{ Ok(v) => v, Err(e) => {{ return Err(e) }} }};",
                reg(*set),
                reg(*index),
                access_kind(*kind)
            );
            wln!("wr(regs, {}, v); code.ip = {next};", reg(*dst));
        }
        Op::GetField {
            dst,
            src,
            slot,
            kind,
        } => {
            wln!("let receiver = rd(regs, {});", reg(*src));
            wln!(
                "if {} == AccessKind::Option && receiver == Val::Null {{",
                access_kind(*kind)
            );
            wln!("    wr(regs, {}, Val::Null); code.ip = {next};", reg(*dst));
            wln!("}} else {{");
            wln!("    let v = match receiver {{");
            wln!("        Val::Instance(i) => i.0.borrow().fields[{slot}],");
            wln!("        Val::Array(a) => a.0.borrow()[{slot}],");
            wln!("        Val::Null => {{ *op_ip = {offset}; return Err(RtErr::UnwrappedNull); }}");
            wln!(
                "        other => {{ *op_ip = {offset}; return Err(RtErr::Custom(format!(\"no fields on {{:?}}\", other.capture()))); }}"
            );
            wln!("    }};");
            wln!("    wr(regs, {}, v); code.ip = {next};", reg(*dst));
            wln!("}}");
        }
        Op::SetField {
            receiver,
            slot,
            value,
        } => {
            wln!("let receiver = rd(regs, {});", reg(*receiver));
            wln!("let value = rd(regs, {});", reg(*value));
            wln!("match receiver {{");
            wln!("    Val::Instance(i) => i.0.borrow_mut(&ctx).fields[{slot}] = value,");
            wln!("    Val::Array(a) => a.0.borrow_mut(&ctx)[{slot}] = value,");
            wln!("    Val::Null => {{ *op_ip = {offset}; return Err(RtErr::UnwrappedNull); }}");
            wln!(
                "    other => {{ *op_ip = {offset}; return Err(RtErr::Custom(format!(\"no fields on {{:?}}\", other.capture()))); }}"
            );
            wln!("}}");
            wln!("code.ip = {next};");
        }
        Op::LoadConst { dst, constant } => match (sh.int(*dst), sh.float(*dst)) {
            (Some(d), _) if matches!(constant, Constant::Int(_)) => {
                let Constant::Int(v) = constant else {
                    unreachable!()
                };
                wln!("{d} = {v}i64; r{}ok = true; code.ip = {next};", dst.index(),);
            }
            (_, Some(d)) if matches!(constant, Constant::Float(_)) => {
                let Constant::Float(v) = constant else {
                    unreachable!()
                };
                wln!(
                    "{d} = f64::from_bits({}u64); r{}ok = true; code.ip = {next};",
                    v.to_bits(),
                    dst.index(),
                );
            }
            _ => {
                wln!(
                    "wr(regs, {}, constant_to_val({}, ctx, strs)); code.ip = {next};",
                    reg(*dst),
                    konst(constant)
                );
            }
        },
        Op::LoadBody { dst, body } => {
            wln!(
                "wr(regs, {}, Val::Fn(BodyId::from({}u32))); code.ip = {next};",
                reg(*dst),
                body.index()
            );
        }
        Op::LoadEntry { dst, slot } => {
            wln!("let base = thread.frames.last().map(|f| f.base).unwrap_or(0);");
            wln!(
                "let v = unsafe {{ *regs.as_ptr().sub(base).add({}) }};",
                slot.index()
            );
            wln!("wr(regs, {}, v); code.ip = {next};", reg(*dst));
        }
        Op::StoreEntry { slot, src } => {
            wln!("let base = thread.frames.last().map(|f| f.base).unwrap_or(0);");
            wln!("let v = rd(regs, {});", reg(*src));
            wln!(
                "unsafe {{ *regs.as_mut_ptr().sub(base).add({}) = v }};",
                slot.index()
            );
            wln!("code.ip = {next};");
        }
        Op::Jump { target } => wln!("{}", tail(tgt(target))),
        Op::JumpIf {
            cond,
            target,
            is_true,
        } => {
            wln!(
                "if rd(regs, {}) == Val::Bool({is_true}) {{ {} }} else {{ {} }}",
                reg(*cond),
                tail(tgt(target)),
                tail(next)
            );
        }
        Op::ForNext { idx, bound, target } => {
            // shadowed-but-flag-clear falls back to `step`, whose arm hits the
            // same `unreachable!` the interpreter would
            let bail =
                format!("*op_ip = {offset}; return step(regs, code, ctx, strs, &thread.frames)");
            let i = match sh.int(*idx) {
                Some(v) => format!("if r{}ok {{ {v} }} else {{ {bail} }}", idx.index()),
                None => format!(
                    "match rd(regs, {}) {{ Val::Int(x) => x, _ => unreachable!(\"for_next idx is statically int\") }}",
                    reg(*idx)
                ),
            };
            let b = match sh.int(*bound) {
                Some(v) => format!("if r{}ok {{ {v} }} else {{ {bail} }}", bound.index()),
                None => format!(
                    "match rd(regs, {}) {{ Val::Int(x) => x, _ => unreachable!(\"for_next bound is statically int\") }}",
                    reg(*bound)
                ),
            };
            wln!("let i = {i} + 1;");
            if sh.int(*idx).is_some() {
                wln!("r{id}i = i; r{id}ok = true; ", id = idx.index());
            } else {
                wln!("wr(regs, {}, Val::Int(i));", reg(*idx));
            }
            wln!(
                "if i < {b} {{ {} }} else {{ {} }}",
                tail(tgt(target)),
                tail(next)
            );
        }
        Op::Switch {
            scrut,
            base,
            default,
            table,
        } => {
            let table_src = table
                .iter()
                .map(|t| tgt(t).to_string())
                .collect::<Vec<_>>()
                .join(", ");
            wln!("code.ip = match rd(regs, {}) {{", reg(*scrut));
            wln!("    Val::Instance(i) => {{");
            wln!("        let idx = i.0.borrow().struct_id.wrapping_sub({base}u32) as usize;");
            wln!(
                "        if idx < {} {{ [{table_src}][idx] }} else {{ {} }}",
                table.len(),
                tgt(default)
            );
            wln!("    }}");
            wln!("    Val::Int(v) => {{");
            wln!("        let idx = v.wrapping_sub({base}i64);");
            wln!(
                "        if idx >= 0 && (idx as usize) < {} {{ [{table_src}][idx as usize] }} else {{ {} }}",
                table.len(),
                tgt(default)
            );
            wln!("    }}");
            wln!("    _ => {},", tgt(default));
            wln!("}};");
        }
        Op::Call { dst, callee, args } => {
            wln!("let target = match rd(regs, {}) {{", reg(*callee));
            wln!("    Val::Fn(b) => CallTarget::Value(b),");
            wln!("    Val::Closure(c) => CallTarget::Closure(c),");
            wln!("    other => {{ *op_ip = {offset}; return Err(not_callable(other)); }}");
            wln!("}};");
            // resolve `(body, captures)` exactly as the driver's `Flow::Call`
            // handling does — the `Value` arm's signature check included
            wln!("let (cb, captures): (BodyId, &[Val]) = match &target {{");
            wln!("    CallTarget::Fn(b) | CallTarget::Value(b) => {{");
            wln!("        if signatures.get(*b).and_then(|o| o.as_ref()).is_none() {{");
            wln!("            *op_ip = {offset}; return Err(not_callable(Val::Fn(*b)));");
            wln!("        }}");
            wln!("        (*b, &[][..])");
            wln!("    }}");
            wln!("    CallTarget::Closure(c) => {{");
            wln!("        let d = Gc::as_ref(c.0);");
            wln!("        (d.function, d.captures.as_slice())");
            wln!("    }}");
            wln!("}};");
            // `enter_call` saves `code.ip` as the caller's resume slot — in the
            // interpreter it's already past this op's operands by then, so the
            // specialized arm must advance it before either path.
            wln!("code.ip = {next}; *op_ip = {offset};");
            emit_call_fast(&mut s, *dst, "cb", "captures", "target", args, sh);
        }
        Op::CallDirect { dst, body, args } => {
            let callee = format!("BodyId::from({}u32)", body.index());
            wln!("code.ip = {next}; *op_ip = {offset};");
            emit_call_fast(
                &mut s,
                *dst,
                &callee,
                "&[]",
                &format!("CallTarget::Fn({callee})"),
                args,
                sh,
            );
        }
        Op::CallNative { dst, id, args } => {
            wln!("let mut args = SmallVec::<[Val; 8]>::new();");
            for a in args {
                wln!("args.push(rd(regs, {}));", reg(*a));
            }
            wln!("let native = {{");
            wln!("    let table = ctx.state().natives.borrow();");
            wln!(
                "    *table.get({}).and_then(|o| o.as_ref()).expect(\"native id has no installed entry\")",
                id.index()
            );
            wln!("}};");
            // the interpreter's debug-mirror refresh runs with `code.ip` just
            // past this call op — `{next}` here, since generated code never decoded
            wln!("{{");
            wln!("    let mut stack = ctx.fixture::<DebugInfo>().stack.borrow_mut();");
            wln!("    stack.clear();");
            wln!("    stack.extend(thread.frames.iter().map(|f| (f.chunk, f.ip as u32)));");
            wln!("    if let Some(top) = stack.last_mut() {{ top.1 = {next}u32; }}");
            wln!("}}");
            wln!("*op_ip = {offset};");
            wln!(
                "let v = match native.call(ctx, &args) {{ Ok(v) => v, Err(e) => {{ return Err(e) }} }};"
            );
            wln!("wr(regs, {}, v);", reg(*dst));
            wln!("code.ip = {next};");
        }
        Op::Return { val } => wln!("return Ok(Flow::Return(rd(regs, {})));", reg(*val)),
        Op::Panic {} => wln!("*op_ip = {offset}; return Err(RtErr::MatchPanicReached);"),
        Op::Raise { val } => {
            wln!(
                "let Val::Str(err) = rd(regs, {}) else {{ unreachable!(\"raise on a non-str value\") }};",
                reg(*val)
            );
            wln!("return Ok(Flow::Return(Val::Raised(err)));");
        }
        Op::IsRaised { dst, src } => {
            wln!(
                "wr(regs, {}, Val::Bool(matches!(rd(regs, {}), Val::Raised(_)))); code.ip = {next};",
                reg(*dst),
                reg(*src)
            );
        }
        Op::UnwrapRaised { dst, src } => {
            wln!(
                "let Val::Raised(err) = rd(regs, {}) else {{ unreachable!(\"UnwrapRaised on non-raised value\") }};",
                reg(*src)
            );
            wln!("wr(regs, {}, Val::Str(err)); code.ip = {next};", reg(*dst));
        }
        Op::Unwrap { dst, src } => {
            wln!("let v = rd(regs, {});", reg(*src));
            wln!("match v {{");
            wln!("    Val::Null => {{ *op_ip = {offset}; return Err(RtErr::UnwrappedNull); }}");
            wln!(
                "    Val::Raised(err) => {{ *op_ip = {offset}; return Err(RtErr::UnwrappedRaised(err.as_str().to_string())); }}"
            );
            wln!("    _ => wr(regs, {}, v),", reg(*dst));
            wln!("}}");
            wln!("code.ip = {next};");
        }
        Op::UnwrapUnit { dst, src } => {
            wln!("match rd(regs, {}) {{", reg(*src));
            wln!(
                "    Val::Raised(err) => {{ *op_ip = {offset}; return Err(RtErr::UnwrappedRaised(err.as_str().to_string())); }}"
            );
            wln!("    _ => wr(regs, {}, Val::Null),", reg(*dst));
            wln!("}}");
            wln!("code.ip = {next};");
        }
        Op::Len { dst, src } => {
            wln!("let len = match rd(regs, {}) {{", reg(*src));
            wln!("    Val::Array(a) => a.0.borrow().len(),");
            wln!("    Val::Dict(d) => d.0.borrow().len(),");
            wln!("    Val::Str(s) => s.as_str().chars().count(),");
            wln!("    Val::Int(i) => i as usize,");
            wln!(
                "    other => {{ *op_ip = {offset}; return Err(RtErr::Custom(format!(\"len: {{:?}} has no length\", other.capture()))); }}"
            );
            wln!("}};");
            if let Some(d) = sh.int(*dst) {
                wln!(
                    "{d} = len as i64; r{}ok = true; code.ip = {next};",
                    dst.index(),
                );
            } else {
                wln!(
                    "wr(regs, {}, Val::Int(len as i64)); code.ip = {next};",
                    reg(*dst)
                );
            }
        }
        Op::ToFloat { dst, src } => {
            let i = match sh.int(*src) {
                Some(v) => format!(
                    "if r{}ok {{ {v} }} else {{ *op_ip = {offset}; return step(regs, code, ctx, strs, &thread.frames) }}",
                    src.index()
                ),
                None => format!(
                    "match rd(regs, {}) {{ Val::Int(x) => x, _ => unreachable!(\"to_float can only be placed on an int by the compiler!\") }}",
                    reg(*src)
                ),
            };
            if let Some(d) = sh.float(*dst) {
                wln!(
                    "{d} = {i} as f64; r{}ok = true; code.ip = {next};",
                    dst.index(),
                );
            } else {
                wln!(
                    "wr(regs, {}, Val::Float({i} as f64)); code.ip = {next};",
                    reg(*dst)
                );
            }
        }
        Op::Sqrt { dst, src } => {
            let f = match sh.float(*src) {
                Some(v) => format!(
                    "if r{}ok {{ {v} }} else {{ *op_ip = {offset}; return step(regs, code, ctx, strs, &thread.frames) }}",
                    src.index()
                ),
                None => format!(
                    "match rd(regs, {}) {{ Val::Float(x) => x, _ => unreachable!(\"to_float can only be placed on a float by the compiler!\") }}",
                    reg(*src)
                ),
            };
            if let Some(d) = sh.float(*dst) {
                wln!(
                    "{d} = {f}.sqrt(); r{}ok = true; code.ip = {next};",
                    dst.index(),
                );
            } else {
                wln!(
                    "wr(regs, {}, Val::Float({f}.sqrt())); code.ip = {next};",
                    reg(*dst)
                );
            }
        }
        Op::In {
            dst,
            needle,
            haystack,
            condition,
        } => {
            wln!(
                "let v = contains(rd(regs, {}), rd(regs, {}), {condition});",
                reg(*needle),
                reg(*haystack)
            );
            wln!("wr(regs, {}, v); code.ip = {next};", reg(*dst));
        }
        Op::IsInstance { dst, src, adt } => {
            wln!(
                "let m = matches!(rd(regs, {}), Val::Instance(i) if i.0.borrow().struct_id == {}u32);",
                reg(*src),
                adt.index()
            );
            wln!("wr(regs, {}, Val::Bool(m)); code.ip = {next};", reg(*dst));
        }
        Op::Format { dst, parts } => {
            wln!("let mut text = String::with_capacity(32);");
            for p in parts {
                match p {
                    OpFormatPart::Literal(id) => {
                        wln!("text.push_str(strs.get(StrId::from({}u32)));", id.index())
                    }
                    OpFormatPart::Value(r) => {
                        wln!("*op_ip = {offset};");
                        wln!(
                            "if let Err(e) = ctx.to_string_into(&mut text, rd(regs, {})) {{ return Err(e) }};",
                            reg(*r)
                        );
                    }
                }
            }
            wln!(
                "wr(regs, {}, Val::Str(ctx.intern(&text))); code.ip = {next};",
                reg(*dst)
            );
        }
        Op::Bin {
            dst,
            left,
            op,
            right,
        } => {
            wln!("*op_ip = {offset};");
            wln!(
                "let v = match bin(rd(regs, {}), ctx, rd(regs, {}), BinOp::{op:?}) {{ Ok(v) => v, Err(e) => {{ return Err(e) }} }};",
                reg(*left),
                reg(*right)
            );
            wln!("wr(regs, {}, v); code.ip = {next};", reg(*dst));
        }
        Op::Unary { dst, op, src } => {
            wln!("*op_ip = {offset};");
            wln!(
                "let v = match unary(rd(regs, {}), ctx, UnaryOp::{op:?}) {{ Ok(v) => v, Err(e) => {{ return Err(e) }} }};",
                reg(*src)
            );
            wln!("wr(regs, {}, v); code.ip = {next};", reg(*dst));
        }
        Op::BoolEq { dst, left, right } => emit_bool(&mut s, *dst, *left, *right, next, "=="),
        Op::BoolNe { dst, left, right } => emit_bool(&mut s, *dst, *left, *right, next, "!="),
        Op::AddInt { dst, left, right } => emit_int_arith(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            "checked_add",
            "Add",
        ),
        Op::SubInt { dst, left, right } => emit_int_arith(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            "checked_sub",
            "Sub",
        ),
        Op::MultInt { dst, left, right } => emit_int_arith(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            "checked_mul",
            "Mult",
        ),
        Op::ModInt { dst, left, right } => {
            let cold = format!(
                "return bin_cold(regs, {}, {}, {}, ctx, BinOp::Mod);",
                reg(*dst),
                reg(*left),
                reg(*right)
            );
            let a = int_opnd(sh, *left, next, offset, &cold);
            let b = int_opnd(sh, *right, next, offset, &cold);
            wln!("let b = {b};");
            wln!("if b == 0 {{ *op_ip = {offset}; return Err(RtErr::ModByZero); }}");
            if let Some(d) = sh.int(*dst) {
                wln!(
                    "{d} = {a} % b; r{}ok = true; code.ip = {next};",
                    dst.index(),
                );
            } else {
                wln!(
                    "wr(regs, {}, Val::Int({a} % b)); code.ip = {next};",
                    reg(*dst)
                );
            }
        }
        Op::IntLt { dst, left, right } => emit_int_eval(
            &mut s, sh, offset, *dst, *left, *right, next, "<", "LessThan",
        ),
        Op::IntLe { dst, left, right } => emit_int_eval(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            "<=",
            "LessEqual",
        ),
        Op::IntGt { dst, left, right } => emit_int_eval(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            ">",
            "GreaterThan",
        ),
        Op::IntGe { dst, left, right } => emit_int_eval(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            ">=",
            "GreaterEqual",
        ),
        Op::IntEq { dst, left, right } => emit_int_eval(
            &mut s, sh, offset, *dst, *left, *right, next, "==", "Identity",
        ),
        Op::IntNe { dst, left, right } => emit_int_eval(
            &mut s, sh, offset, *dst, *left, *right, next, "!=", "NotEqual",
        ),
        Op::AddFloat { dst, left, right } => {
            emit_float_arith(&mut s, sh, offset, *dst, *left, *right, next, "+", "Add")
        }
        Op::SubFloat { dst, left, right } => {
            emit_float_arith(&mut s, sh, offset, *dst, *left, *right, next, "-", "Sub")
        }
        Op::MultFloat { dst, left, right } => {
            emit_float_arith(&mut s, sh, offset, *dst, *left, *right, next, "*", "Mult")
        }
        Op::DivFloat { dst, left, right } => {
            emit_float_arith(&mut s, sh, offset, *dst, *left, *right, next, "/", "Div")
        }
        Op::FloatLt { dst, left, right } => emit_float_eval(
            &mut s, sh, offset, *dst, *left, *right, next, "<", "LessThan",
        ),
        Op::FloatLe { dst, left, right } => emit_float_eval(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            "<=",
            "LessEqual",
        ),
        Op::FloatGt { dst, left, right } => emit_float_eval(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            ">",
            "GreaterThan",
        ),
        Op::FloatGe { dst, left, right } => emit_float_eval(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            ">=",
            "GreaterEqual",
        ),
        Op::FloatEq { dst, left, right } => emit_float_eval(
            &mut s, sh, offset, *dst, *left, *right, next, "==", "Identity",
        ),
        Op::FloatNe { dst, left, right } => emit_float_eval(
            &mut s, sh, offset, *dst, *left, *right, next, "!=", "NotEqual",
        ),
        Op::StrEq { dst, left, right } => {
            emit_str_eval(&mut s, offset, *dst, *left, *right, next, "==", "Identity")
        }
        Op::StrNe { dst, left, right } => {
            emit_str_eval(&mut s, offset, *dst, *left, *right, next, "!=", "NotEqual")
        }
        Op::AddIntImm { dst, left, val } => emit_int_arith_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            "checked_add",
            "Add",
        ),
        Op::SubIntImm { dst, left, val } => emit_int_arith_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            "checked_sub",
            "Sub",
        ),
        Op::MultIntImm { dst, left, val } => emit_int_arith_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            "checked_mul",
            "Mult",
        ),
        Op::ModIntImm { dst, left, val } => {
            let a = int_opnd(
                sh,
                *left,
                next,
                offset,
                &format!(
                    "return bin_cold_imm_int(regs, {}, {}, {val}i64, ctx, BinOp::Mod);",
                    reg(*dst),
                    reg(*left)
                ),
            );
            wln!("if {val}i64 == 0 {{ *op_ip = {offset}; return Err(RtErr::ModByZero); }}");
            if let Some(d) = sh.int(*dst) {
                wln!(
                    "{d} = {a} % {val}i64; r{}ok = true; code.ip = {next};",
                    dst.index(),
                );
            } else {
                wln!(
                    "wr(regs, {}, Val::Int({a} % {val}i64)); code.ip = {next};",
                    reg(*dst)
                );
            }
        }
        Op::IntLtImm { dst, left, val } => {
            emit_int_eval_imm(&mut s, sh, offset, *dst, *left, *val, next, "<", "LessThan")
        }
        Op::IntLeImm { dst, left, val } => emit_int_eval_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            "<=",
            "LessEqual",
        ),
        Op::IntGtImm { dst, left, val } => emit_int_eval_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            ">",
            "GreaterThan",
        ),
        Op::IntGeImm { dst, left, val } => emit_int_eval_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            ">=",
            "GreaterEqual",
        ),
        Op::IntEqImm { dst, left, val } => emit_int_eval_imm(
            &mut s, sh, offset, *dst, *left, *val, next, "==", "Identity",
        ),
        Op::IntNeImm { dst, left, val } => emit_int_eval_imm(
            &mut s, sh, offset, *dst, *left, *val, next, "!=", "NotEqual",
        ),
        Op::BIntLt {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Int",
            "<",
            "LessThan",
            tail,
        ),
        Op::BIntLe {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Int",
            "<=",
            "LessEqual",
            tail,
        ),
        Op::BIntGt {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Int",
            ">",
            "GreaterThan",
            tail,
        ),
        Op::BIntGe {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Int",
            ">=",
            "GreaterEqual",
            tail,
        ),
        Op::BIntEq {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Int",
            "==",
            "Identity",
            tail,
        ),
        Op::BIntNe {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Int",
            "!=",
            "NotEqual",
            tail,
        ),
        Op::BIntLtImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, false)),
            *is_true,
            "Val::Int",
            "<",
            "LessThan",
            tail,
        ),
        Op::BIntLeImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, false)),
            *is_true,
            "Val::Int",
            "<=",
            "LessEqual",
            tail,
        ),
        Op::BIntGtImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, false)),
            *is_true,
            "Val::Int",
            ">",
            "GreaterThan",
            tail,
        ),
        Op::BIntGeImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, false)),
            *is_true,
            "Val::Int",
            ">=",
            "GreaterEqual",
            tail,
        ),
        Op::BIntEqImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, false)),
            *is_true,
            "Val::Int",
            "==",
            "Identity",
            tail,
        ),
        Op::BIntNeImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, false)),
            *is_true,
            "Val::Int",
            "!=",
            "NotEqual",
            tail,
        ),
        Op::BFloatLt {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Float",
            "<",
            "LessThan",
            tail,
        ),
        Op::BFloatLe {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Float",
            "<=",
            "LessEqual",
            tail,
        ),
        Op::BFloatGt {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Float",
            ">",
            "GreaterThan",
            tail,
        ),
        Op::BFloatGe {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Float",
            ">=",
            "GreaterEqual",
            tail,
        ),
        Op::BFloatEq {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Float",
            "==",
            "Identity",
            tail,
        ),
        Op::BFloatNe {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Float",
            "!=",
            "NotEqual",
            tail,
        ),
        Op::BFloatLtImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, true)),
            *is_true,
            "Val::Float",
            "<",
            "LessThan",
            tail,
        ),
        Op::BFloatLeImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, true)),
            *is_true,
            "Val::Float",
            "<=",
            "LessEqual",
            tail,
        ),
        Op::BFloatGtImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, true)),
            *is_true,
            "Val::Float",
            ">",
            "GreaterThan",
            tail,
        ),
        Op::BFloatGeImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, true)),
            *is_true,
            "Val::Float",
            ">=",
            "GreaterEqual",
            tail,
        ),
        Op::BFloatEqImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, true)),
            *is_true,
            "Val::Float",
            "==",
            "Identity",
            tail,
        ),
        Op::BFloatNeImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, true)),
            *is_true,
            "Val::Float",
            "!=",
            "NotEqual",
            tail,
        ),
        Op::AddFloatImm { dst, left, val } => {
            emit_float_arith_imm(&mut s, sh, offset, *dst, *left, *val, next, "+", "Add")
        }
        Op::SubFloatImm { dst, left, val } => {
            emit_float_arith_imm(&mut s, sh, offset, *dst, *left, *val, next, "-", "Sub")
        }
        Op::MultFloatImm { dst, left, val } => {
            emit_float_arith_imm(&mut s, sh, offset, *dst, *left, *val, next, "*", "Mult")
        }
        Op::ModFloatImm { dst, left, val } => {
            emit_float_arith_imm(&mut s, sh, offset, *dst, *left, *val, next, "%", "Mod")
        }
        Op::FloatLtImm { dst, left, val } => {
            emit_float_eval_imm(&mut s, sh, offset, *dst, *left, *val, next, "<", "LessThan")
        }
        Op::FloatLeImm { dst, left, val } => emit_float_eval_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            "<=",
            "LessEqual",
        ),
        Op::FloatGtImm { dst, left, val } => emit_float_eval_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            ">",
            "GreaterThan",
        ),
        Op::FloatGeImm { dst, left, val } => emit_float_eval_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            ">=",
            "GreaterEqual",
        ),
        Op::FloatEqImm { dst, left, val } => emit_float_eval_imm(
            &mut s, sh, offset, *dst, *left, *val, next, "==", "Identity",
        ),
        Op::FloatNeImm { dst, left, val } => emit_float_eval_imm(
            &mut s, sh, offset, *dst, *left, *val, next, "!=", "NotEqual",
        ),
    }
    let _ = write!(w, "{s}");
}

fn emit_bool(s: &mut String, dst: Reg, left: Reg, right: Reg, next: usize, op: &str) {
    let name = if op == "==" { "eq" } else { "ne" };
    let _ = writeln!(
        s,
        "let Val::Bool(l) = rd(regs, {}) else {{ unreachable!(\"illegal bool {name} op\") }};\n\
         let Val::Bool(r) = rd(regs, {}) else {{ unreachable!(\"illegal bool {name} op\") }};\n\
         wr(regs, {}, Val::Bool(l {op} r)); code.ip = {next};",
        reg(left),
        reg(right),
        reg(dst),
    );
}

// Below, the emit_* fns write the arm's *contents* into `s` and `emit_op` wraps
// it in `{offset} => {{ ... }}`. Operand expressions come from `int_opnd` /
// `float_opnd`: a shadow-local name when unboxed, else a `regs` match whose
// miss arm pre-advances `code.ip`, stores `*op_ip`, and tail-calls the same
// `bin_cold*`/`branch_cold*` helper the interpreter's macro would have reached.

#[allow(clippy::too_many_arguments)]
fn emit_int_arith(
    s: &mut String,
    sh: &Sh,
    off: usize,
    dst: Reg,
    left: Reg,
    right: Reg,
    next: usize,
    checked: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold(regs, {}, {}, {}, ctx, BinOp::{binop});",
        reg(dst),
        reg(left),
        reg(right)
    );
    let a = int_opnd(sh, left, next, off, &cold);
    let b = int_opnd(sh, right, next, off, &cold);
    let _ = writeln!(
        s,
        "let Some(v) = ({a}).{checked}({b}) else {{ *op_ip = {off}; return Err(RtErr::IntegerOverflow) }};"
    );
    sh.wr_shadow(s, dst, "Int", "v");
    let _ = writeln!(s, "code.ip = {next};");
}

#[allow(clippy::too_many_arguments)]
fn emit_int_eval(
    s: &mut String,
    sh: &Sh,
    off: usize,
    dst: Reg,
    left: Reg,
    right: Reg,
    next: usize,
    op: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold(regs, {}, {}, {}, ctx, BinOp::{binop});",
        reg(dst),
        reg(left),
        reg(right)
    );
    let a = int_opnd(sh, left, next, off, &cold);
    let b = int_opnd(sh, right, next, off, &cold);
    let _ = writeln!(
        s,
        "wr(regs, {}, Val::Bool({a} {op} {b})); code.ip = {next};",
        reg(dst)
    );
}

#[allow(clippy::too_many_arguments)]
fn emit_float_arith(
    s: &mut String,
    sh: &Sh,
    off: usize,
    dst: Reg,
    left: Reg,
    right: Reg,
    next: usize,
    op: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold(regs, {}, {}, {}, ctx, BinOp::{binop});",
        reg(dst),
        reg(left),
        reg(right)
    );
    let a = float_opnd(sh, left, next, off, &cold);
    let b = float_opnd(sh, right, next, off, &cold);
    sh.wr_shadow(s, dst, "Float", &format!("({a}) {op} ({b})"));
    let _ = writeln!(s, "code.ip = {next};");
}

#[allow(clippy::too_many_arguments)]
fn emit_float_eval(
    s: &mut String,
    sh: &Sh,
    off: usize,
    dst: Reg,
    left: Reg,
    right: Reg,
    next: usize,
    op: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold(regs, {}, {}, {}, ctx, BinOp::{binop});",
        reg(dst),
        reg(left),
        reg(right)
    );
    let a = float_opnd(sh, left, next, off, &cold);
    let b = float_opnd(sh, right, next, off, &cold);
    let _ = writeln!(
        s,
        "wr(regs, {}, Val::Bool({a} {op} {b})); code.ip = {next};",
        reg(dst)
    );
}

fn emit_str_eval(
    s: &mut String,
    off: usize,
    dst: Reg,
    left: Reg,
    right: Reg,
    next: usize,
    op: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold(regs, {}, {}, {}, ctx, BinOp::{binop});",
        reg(dst),
        reg(left),
        reg(right)
    );
    let _ = writeln!(
        s,
        "match (rd(regs, {l}), rd(regs, {r})) {{\n\
         (Val::Str(a), Val::Str(b)) => {{ wr(regs, {d}, Val::Bool(a {op} b)); code.ip = {next}; }}\n\
         _ => {{ code.ip = {next}; *op_ip = {off}; {cold} }}\n\
         }}",
        l = reg(left),
        r = reg(right),
        d = reg(dst),
    );
}

#[allow(clippy::too_many_arguments)]
fn emit_int_arith_imm(
    s: &mut String,
    sh: &Sh,
    off: usize,
    dst: Reg,
    left: Reg,
    val: i64,
    next: usize,
    checked: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold_imm_int(regs, {}, {}, {val}i64, ctx, BinOp::{binop});",
        reg(dst),
        reg(left)
    );
    let a = int_opnd(sh, left, next, off, &cold);
    let _ = writeln!(
        s,
        "let Some(v) = ({a}).{checked}({val}i64) else {{ *op_ip = {off}; return Err(RtErr::IntegerOverflow) }};"
    );
    sh.wr_shadow(s, dst, "Int", "v");
    let _ = writeln!(s, "code.ip = {next};");
}

#[allow(clippy::too_many_arguments)]
fn emit_int_eval_imm(
    s: &mut String,
    sh: &Sh,
    off: usize,
    dst: Reg,
    left: Reg,
    val: i64,
    next: usize,
    op: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold_imm_int(regs, {}, {}, {val}i64, ctx, BinOp::{binop});",
        reg(dst),
        reg(left)
    );
    let a = int_opnd(sh, left, next, off, &cold);
    let _ = writeln!(
        s,
        "wr(regs, {}, Val::Bool({a} {op} {val}i64)); code.ip = {next};",
        reg(dst)
    );
}

#[allow(clippy::too_many_arguments)]
fn emit_float_arith_imm(
    s: &mut String,
    sh: &Sh,
    off: usize,
    dst: Reg,
    left: Reg,
    val: i64,
    next: usize,
    op: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold_imm_float(regs, {}, {}, f64::from_bits({val}i64 as u64), ctx, BinOp::{binop});",
        reg(dst),
        reg(left)
    );
    let a = float_opnd(sh, left, next, off, &cold);
    sh.wr_shadow(
        s,
        dst,
        "Float",
        &format!("({a}) {op} f64::from_bits({val}i64 as u64)"),
    );
    let _ = writeln!(s, "code.ip = {next};");
}

#[allow(clippy::too_many_arguments)]
fn emit_float_eval_imm(
    s: &mut String,
    sh: &Sh,
    off: usize,
    dst: Reg,
    left: Reg,
    val: i64,
    next: usize,
    op: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold_imm_float(regs, {}, {}, f64::from_bits({val}i64 as u64), ctx, BinOp::{binop});",
        reg(dst),
        reg(left)
    );
    let a = float_opnd(sh, left, next, off, &cold);
    let _ = writeln!(
        s,
        "wr(regs, {}, Val::Bool({a} {op} f64::from_bits({val}i64 as u64))); code.ip = {next};",
        reg(dst)
    );
}

/// The `B*` branch family — `right` for the register variant, `imm` for the
/// immediate one (`is_float` picks the `f64::from_bits` decode). A mismatched
/// operand type pre-advances `code.ip` and tail-calls the `branch_cold*`
/// helper the interpreter's own macro would have reached.
#[allow(clippy::too_many_arguments)]
fn emit_branch(
    s: &mut String,
    sh: &Sh,
    off: usize,
    next: usize,
    target: &BlockTarget,
    left: Reg,
    right: Option<Reg>,
    imm: Option<(i64, bool)>,
    is_true: bool,
    variant: &str,
    op: &str,
    binop: &str,
    tail: &dyn Fn(usize) -> String,
) {
    let t = tgt(target);
    let int = variant == "Val::Int";
    let hit = if let Some(r) = right {
        let cold = format!(
            "return branch_cold(regs, code, {t}, {is_true}, {}, {}, ctx, BinOp::{binop});",
            reg(left),
            reg(r)
        );
        let a = if int {
            int_opnd(sh, left, next, off, &cold)
        } else {
            float_opnd(sh, left, next, off, &cold)
        };
        let b = if int {
            int_opnd(sh, r, next, off, &cold)
        } else {
            float_opnd(sh, r, next, off, &cold)
        };
        format!("{a} {op} {b}")
    } else if let Some((val, true)) = imm {
        let cold = format!(
            "return branch_cold_imm_float(regs, code, {t}, {is_true}, {}, f64::from_bits({val}i64 as u64), ctx, BinOp::{binop});",
            reg(left)
        );
        let a = float_opnd(sh, left, next, off, &cold);
        format!("{a} {op} f64::from_bits({val}i64 as u64)")
    } else {
        let (val, _) = imm.unwrap();
        let cold = format!(
            "return branch_cold_imm_int(regs, code, {t}, {is_true}, {}, {val}i64, ctx, BinOp::{binop});",
            reg(left)
        );
        let a = int_opnd(sh, left, next, off, &cold);
        format!("{a} {op} {val}i64")
    };
    let _ = writeln!(s, "let hit = {hit};");
    let _ = writeln!(
        s,
        "if hit == {is_true} {{ {} }} else {{ {} }}",
        tail(t),
        tail(next)
    );
}
