//! Futamura-1 specialization of the mimas interpreter: given a compiled
//! [`Program`], emit one Rust fn per bytecode body — a `step_one` specialized to
//! that body's fixed op stream, with operands already folded to literals.
//!
//! The emitted module is consumed by `Vm::install_bc`:
//!
//! ```ignore
//! let (program, sources) = Vm::compile_parts(files, std_install)?;
//! let src = bcgen::emit(&program, "mimas::vm");   // the generated module
//! // ... write `src` into a crate that deps `mimas`, build it, and inside it:
//! vm.load_prebuilt(program, sources, std_install);
//! vm.install_bc(generated::bodies());
//! vm.run() // executes specialized bodies, interpreter for everything else
//! ```
//!
//! Two levels of specialization, both single-sourced against the interpreter:
//!
//! * **Ops.** Every op arm reproduces `step_one`'s statement-for-statement, and every *cold path
//!   inside* an arm tail-calls the same `bin_cold`/`branch_cold` helper the interpreter's own
//!   macros reach (with `code.ip` pre-advanced, since generated code never decodes). The `_ =>`
//!   catch-all delegates to `step` — the real `step_one` — for ops no emitter covers.
//! * **Registers.** A register whose writers all produce one scalar kind (int/float) gets a native
//!   Rust local shadowing it, *write-through*: every shadow update also stores the `Val` into
//!   `regs`, so `regs` stays authoritative and any op, call, native, or `step` fallback always sees
//!   the truth. A body entering with a shadowed register holding a non-scalar `Val` (a mistyped
//!   call argument, an uninitialized slot) bails that one op to `step` — the interpreter runs it
//!   verbatim and the program continues.
//!
//! Bodies loop internally: fuel, op budget, and the pause flag are consumed
//! per op exactly as `run_dispatch` does, and `Flow::Call`/`Flow::Return`/errors
//! end the body's turn for the driver's frame transitions.

use std::{
    collections::{HashMap, HashSet},
    fmt::Write,
};

use compile::{BlockTarget, Constant, Op, OpFormatPart, Program, Reg};

/// Emit the specialized-bodies module for `program`. `vm` is the path the
/// generated module uses to reach the vm crate's `bc` module — `"mimas::vm"`
/// under the `mimas` facade, `"vm"` for a direct `mimas-vm` dep.
pub fn emit(program: &Program, vm: &str) -> String {
    let mut w = String::new();
    // `//` rather than `//!` so the file can also live inside `include!`d
    // module blocks, where inner doc comments are rejected.
    let _ = writeln!(
        w,
        "// Generated by mimas-bcgen — chunk-specialized `step_one` bodies for one\n\
         // fixed program. Do not edit; regenerate from the source instead.\n\
         // Ops without a specialization below call `step`, the interpreter's own\n\
         // dispatch, so coverage is always total.\n\
         // (inner `#![allow]`s aren't permitted inside `include!`, so the\n\
         // allows live on the items themselves.)\n\
         #[allow(unused_imports)]\n\
         use {vm}::bc::*;\n"
    );
    for (body, _) in program.chunks.iter() {
        emit_body(&mut w, program, body.index());
    }
    let _ = writeln!(
        w,
        "\n/// The install table for `Vm::install_bc`, indexed by `BodyId`."
    );
    let _ = writeln!(w, "pub fn bodies() -> Vec<Option<BodyFn>> {{");
    let _ = writeln!(w, "    vec![");
    for (body, _) in program.chunks.iter() {
        let _ = writeln!(w, "        Some(body_{}),", body.index());
    }
    let _ = writeln!(w, "    ]");
    let _ = writeln!(w, "}}");
    w
}

/// What scalar kind a writer produces for its destination register.
#[derive(Clone, Copy, PartialEq)]
enum W {
    Int,
    Float,
    /// The written value copies another register — inherits its class.
    Copy(u32),
    /// Anything else: the register isn't eligible for a scalar shadow.
    Dyn,
}

/// Registers safe to shadow as native scalars for one body.
///
/// A register joins `int` when *every* op that can write it provably produces
/// `Val::Int` — including vacuous membership (parameters and other never-written
/// registers, whose entry value is checked once at body entry). `Copy(src)`
/// writers adopt `src`'s class, so membership resolves by fixpoint.
struct Sh {
    int: HashSet<u32>,
    float: HashSet<u32>,
}

impl Sh {
    /// The shadow local's name if `r` is int-shadowed.
    fn int(&self, r: Reg) -> Option<String> {
        self.int
            .contains(&(r.index() as u32))
            .then(|| format!("r{}i", r.index()))
    }
    fn float(&self, r: Reg) -> Option<String> {
        self.float
            .contains(&(r.index() as u32))
            .then(|| format!("r{}f", r.index()))
    }
    /// Scalar-write: `valexpr` is a bare `i64`/`f64` — shadowed registers update
    /// the local, set its flag, and write the tagged `Val` through; unshadowed
    /// ones just wrap.
    fn wr_shadow(&self, s: &mut String, r: Reg, kind: &str, valexpr: &str) {
        if let Some(v) = self.int(r) {
            let _ = writeln!(
                s,
                "{v} = {valexpr}; r{idx}ok = true; wr(regs, {}, Val::Int({v}));",
                reg(r),
                idx = r.index()
            );
        } else if let Some(v) = self.float(r) {
            let _ = writeln!(
                s,
                "{v} = {valexpr}; r{idx}ok = true; wr(regs, {}, Val::Float({v}));",
                reg(r),
                idx = r.index()
            );
        } else {
            let _ = writeln!(s, "wr(regs, {}, Val::{kind}({valexpr}));", reg(r));
        }
    }
}

/// Register-write classes for one body — every `dst` (plus `ForNext`'s `idx`,
/// which ForNext itself increments) the body's ops can store to, and which
/// registers occupy int/float-typed operand positions (typed reads).
fn analyze(ops: &[(usize, Op)], nregs: u32) -> Sh {
    let mut writes: HashMap<u32, Vec<W>> = HashMap::new();
    let mut put = |r: Reg, w: W| writes.entry(r.index() as u32).or_default().push(w);
    let mut int_reads: HashSet<u32> = HashSet::new();
    let mut float_reads: HashSet<u32> = HashSet::new();
    let mut iread = |r: Reg| {
        int_reads.insert(r.index() as u32);
    };
    let mut fread = |r: Reg| {
        float_reads.insert(r.index() as u32);
    };
    for (_, op) in ops {
        match op {
            Op::Move { dst, src } => put(*dst, W::Copy(src.index() as u32)),
            Op::LoadConst { dst, constant } => put(
                *dst,
                match constant {
                    Constant::Int(_) => W::Int,
                    Constant::Float(_) => W::Float,
                    _ => W::Dyn,
                },
            ),
            Op::AddInt { dst, left, right }
            | Op::SubInt { dst, left, right }
            | Op::MultInt { dst, left, right }
            | Op::ModInt { dst, left, right }
            | Op::IntLt { dst, left, right }
            | Op::IntLe { dst, left, right }
            | Op::IntGt { dst, left, right }
            | Op::IntGe { dst, left, right }
            | Op::IntEq { dst, left, right }
            | Op::IntNe { dst, left, right } => {
                iread(*left);
                iread(*right);
                put(
                    *dst,
                    if matches!(
                        op,
                        Op::AddInt { .. }
                            | Op::SubInt { .. }
                            | Op::MultInt { .. }
                            | Op::ModInt { .. }
                    ) {
                        W::Int
                    } else {
                        W::Dyn
                    },
                );
            }
            Op::AddIntImm { dst, left, .. }
            | Op::SubIntImm { dst, left, .. }
            | Op::MultIntImm { dst, left, .. }
            | Op::ModIntImm { dst, left, .. } => {
                iread(*left);
                put(*dst, W::Int);
            }
            Op::IntLtImm { dst, left, .. }
            | Op::IntLeImm { dst, left, .. }
            | Op::IntGtImm { dst, left, .. }
            | Op::IntGeImm { dst, left, .. }
            | Op::IntEqImm { dst, left, .. }
            | Op::IntNeImm { dst, left, .. } => {
                iread(*left);
                put(*dst, W::Dyn);
            }
            Op::AddFloat { dst, left, right }
            | Op::SubFloat { dst, left, right }
            | Op::MultFloat { dst, left, right }
            | Op::DivFloat { dst, left, right } => {
                fread(*left);
                fread(*right);
                put(*dst, W::Float);
            }
            Op::FloatLt { dst, left, right }
            | Op::FloatLe { dst, left, right }
            | Op::FloatGt { dst, left, right }
            | Op::FloatGe { dst, left, right }
            | Op::FloatEq { dst, left, right }
            | Op::FloatNe { dst, left, right } => {
                fread(*left);
                fread(*right);
                put(*dst, W::Dyn);
            }
            Op::AddFloatImm { dst, left, .. }
            | Op::SubFloatImm { dst, left, .. }
            | Op::MultFloatImm { dst, left, .. }
            | Op::ModFloatImm { dst, left, .. } => {
                fread(*left);
                put(*dst, W::Float);
            }
            Op::FloatLtImm { dst, left, .. }
            | Op::FloatLeImm { dst, left, .. }
            | Op::FloatGtImm { dst, left, .. }
            | Op::FloatGeImm { dst, left, .. }
            | Op::FloatEqImm { dst, left, .. }
            | Op::FloatNeImm { dst, left, .. } => {
                fread(*left);
                put(*dst, W::Dyn);
            }
            Op::Len { dst, .. } => put(*dst, W::Int),
            Op::ToFloat { dst, src } => {
                iread(*src);
                put(*dst, W::Float);
            }
            Op::Sqrt { dst, src } => {
                fread(*src);
                put(*dst, W::Float);
            }
            Op::ForNext { idx, bound, .. } => {
                iread(*idx);
                iread(*bound);
                put(*idx, W::Int);
            }
            Op::BIntLt { left, right, .. }
            | Op::BIntLe { left, right, .. }
            | Op::BIntGt { left, right, .. }
            | Op::BIntGe { left, right, .. }
            | Op::BIntEq { left, right, .. }
            | Op::BIntNe { left, right, .. } => {
                iread(*left);
                iread(*right);
            }
            Op::BIntLtImm { left, .. }
            | Op::BIntLeImm { left, .. }
            | Op::BIntGtImm { left, .. }
            | Op::BIntGeImm { left, .. }
            | Op::BIntEqImm { left, .. }
            | Op::BIntNeImm { left, .. } => iread(*left),
            Op::BFloatLt { left, right, .. }
            | Op::BFloatLe { left, right, .. }
            | Op::BFloatGt { left, right, .. }
            | Op::BFloatGe { left, right, .. }
            | Op::BFloatEq { left, right, .. }
            | Op::BFloatNe { left, right, .. } => {
                fread(*left);
                fread(*right);
            }
            Op::BFloatLtImm { left, .. }
            | Op::BFloatLeImm { left, .. }
            | Op::BFloatGtImm { left, .. }
            | Op::BFloatGeImm { left, .. }
            | Op::BFloatEqImm { left, .. }
            | Op::BFloatNeImm { left, .. } => fread(*left),
            // every other op that carries a dst writes a dynamically-typed
            // value (bools, strings, calls, collections, ...)
            Op::GetField { dst, .. }
            | Op::GetIndex { dst, .. }
            | Op::LoadBody { dst, .. }
            | Op::LoadEntry { dst, .. }
            | Op::BoolEq { dst, .. }
            | Op::BoolNe { dst, .. }
            | Op::StrEq { dst, .. }
            | Op::StrNe { dst, .. }
            | Op::Bin { dst, .. }
            | Op::Unary { dst, .. }
            | Op::In { dst, .. }
            | Op::IsInstance { dst, .. }
            | Op::IsRaised { dst, .. }
            | Op::UnwrapRaised { dst, .. }
            | Op::Unwrap { dst, .. }
            | Op::UnwrapUnit { dst, .. }
            | Op::NewArray { dst }
            | Op::NewDict { dst }
            | Op::NewInstance { dst, .. }
            | Op::NewClosure { dst, .. }
            | Op::Format { dst, .. }
            | Op::Call { dst, .. }
            | Op::CallDirect { dst, .. }
            | Op::CallNative { dst, .. } => put(*dst, W::Dyn),
            // no register destination
            Op::Jump { .. }
            | Op::JumpIf { .. }
            | Op::Switch { .. }
            | Op::Push { .. }
            | Op::Insert { .. }
            | Op::SetIndex { .. }
            | Op::SetField { .. }
            | Op::StoreEntry { .. }
            | Op::Return { .. }
            | Op::Panic {}
            | Op::Raise { .. } => {}
        }
    }

    let mut int: HashSet<u32> = HashSet::new();
    let mut float: HashSet<u32> = HashSet::new();
    // Phase 1: never-written registers (params, scratch) — the only writers
    // can't pin a class, so the *reads* decide. An unwritten reg shadowed as
    // int that actually holds a float at runtime bails to `step` at body
    // entry, so at most one of the two sets claims it.
    for r in 0..nregs {
        if writes.contains_key(&r) {
            continue;
        }
        match (int_reads.contains(&r), float_reads.contains(&r)) {
            (true, false) => {
                int.insert(r);
            }
            (false, true) => {
                float.insert(r);
            }
            _ => {}
        }
    }
    // Phase 2 fixpoint: a written reg shadows as int iff every writer produces
    // Int or Copies an int-set member (likewise float).
    loop {
        let mut changed = false;
        for (&r, ws) in &writes {
            let ok_i = ws.iter().all(|w| match w {
                W::Int => true,
                W::Copy(src) => int.contains(src),
                _ => false,
            });
            let ok_f = ws.iter().all(|w| match w {
                W::Float => true,
                W::Copy(src) => float.contains(src),
                _ => false,
            });
            if ok_i != int.contains(&r) {
                if ok_i {
                    int.insert(r);
                } else {
                    int.remove(&r);
                }
                changed = true;
            }
            if ok_f != float.contains(&r) {
                if ok_f {
                    float.insert(r);
                } else {
                    float.remove(&r);
                }
                changed = true;
            }
        }
        if !changed {
            break;
        }
    }
    Sh { int, float }
}

fn emit_body(w: &mut String, program: &Program, body: usize) {
    let body_id = compile::BodyId::from(body as u32);
    let ops = program.ops(body_id);
    let sh = analyze(&ops, program.chunks[body_id].regs as u32);
    let _ = writeln!(
        w,
        "\n#[allow(unused_variables, unused_mut, unused_assignments, unused_comparisons, clippy::all)]\n\
         fn body_{body}<'gc>(\n\
         \x20   regs: &mut [Val<'gc>],\n\
         \x20   code: &mut Decoder,\n\
         \x20   ctx: Ctx<'gc>,\n\
         \x20   strs: &StrInterner,\n\
         \x20   frames: &[Frame],\n\
         \x20   ops_left: &mut u64,\n\
         \x20   fuel: &mut usize,\n\
         \x20   op_ip: &mut usize,\n\
         ) -> RtResult<Flow<'gc>> {{"
    );
    // Shadowed registers are initialized once per invocation, straight from
    // `regs` — which is authoritative even mid-body thanks to write-through.
    // Each shadow carries an `ok` flag: a non-matching entry value (mistyped
    // call arg, uninitialized slot) just leaves the flag false and reads take
    // the op's own cold path — exactly what the interpreter's tag-miss does.
    for &r in &sh.int {
        let _ = writeln!(
            w,
            "    let (mut r{r}i, mut r{r}ok) = match rd(regs, Reg::from({r}u32)) {{\n\
             \x20       Val::Int(v) => (v, true),\n\
             \x20       _ => (0i64, false),\n\
             \x20   }};"
        );
    }
    for &r in &sh.float {
        let _ = writeln!(
            w,
            "    let (mut r{r}f, mut r{r}ok) = match rd(regs, Reg::from({r}u32)) {{\n\
             \x20       Val::Float(v) => (v, true),\n\
             \x20       _ => (0.0f64, false),\n\
             \x20   }};"
        );
    }
    // The driver's per-op bookkeeping, verbatim and in its own order. A body
    // that exits here leaves `code.ip` at the next unexecuted op, so the
    // driver re-enters cleanly — including its own paused/fuel top-checks.
    let _ = writeln!(w, "    loop {{");
    let _ = writeln!(
        w,
        "        if ctx.state().paused.get() || *fuel == 0 {{ return Ok(Flow::Next); }}\n\
         \x20       *fuel -= 1;\n\
         \x20       if *ops_left == 0 {{ *op_ip = code.ip; return Err(RtErr::OutOfFuel); }}\n\
         \x20       *ops_left -= 1;"
    );
    let _ = writeln!(w, "        match code.ip {{");
    for (i, (offset, op)) in ops.iter().enumerate() {
        let next = ops.get(i + 1).map(|(o, _)| *o).unwrap_or(usize::MAX);
        emit_op(w, &sh, *offset, next, op);
    }
    // an ip outside the chunk's op stream can only come from a codegen bug --
    // hand it to the interpreter, which hits the same garbage decode either way
    let _ = writeln!(
        w,
        "            _ => {{ *op_ip = code.ip; return step(regs, code, ctx, strs, frames); }}"
    );
    let _ = writeln!(w, "        }}");
    let _ = writeln!(w, "    }}");
    let _ = writeln!(w, "}}");
}

fn reg(r: Reg) -> String {
    format!("Reg::from({}u32)", r.index())
}

fn tgt(t: &BlockTarget) -> usize {
    let BlockTarget::ByteOffset(o) = t else {
        panic!("unresolved BlockTarget in compiled program")
    };
    *o
}

fn access_kind(k: compile::AccessKind) -> &'static str {
    match k {
        compile::AccessKind::Direct => "AccessKind::Direct",
        compile::AccessKind::Option => "AccessKind::Option",
    }
}

/// A `Constant` operand as a Rust expression — `constant_to_val(<this>, ctx,
/// strs)` is exactly what the interpreter's `LoadConst` arm runs.
fn konst(c: &Constant) -> String {
    match c {
        Constant::Null => "Constant::Null".to_string(),
        Constant::Bool(b) => format!("Constant::Bool({b})"),
        Constant::Int(i) => format!("Constant::Int({i}i64)"),
        Constant::Float(f) => format!("Constant::Float(f64::from_bits({}u64))", f.to_bits()),
        Constant::Str(id) => format!("Constant::Str(StrId::from({}u32))", id.index()),
        Constant::Array(items) => {
            let items = items.iter().map(konst).collect::<Vec<_>>().join(", ");
            format!("Constant::Array(vec![{items}])")
        }
    }
}

/// An `i64`-producing expression for an int operand: the shadow local when `r`
/// is unboxed, else a `regs` match whose miss arm tail-calls `cold` verbatim.
/// `cold` must be a complete `return ...;` statement.
fn int_opnd(sh: &Sh, r: Reg, next: usize, off: usize, cold: &str) -> String {
    match sh.int(r) {
        // flag-clear means `regs[r]` holds a non-Int right now — take the same
        // cold path the interpreter's tag-miss would
        Some(v) => format!(
            "if r{idx}ok {{ {v} }} else {{ code.ip = {next}; *op_ip = {off}; {cold} }}",
            idx = r.index()
        ),
        None => format!(
            "match rd(regs, {}) {{ Val::Int(x) => x, _ => {{ code.ip = {next}; *op_ip = {off}; {cold} }} }}",
            reg(r)
        ),
    }
}

fn float_opnd(sh: &Sh, r: Reg, next: usize, off: usize, cold: &str) -> String {
    match sh.float(r) {
        Some(v) => format!(
            "if r{idx}ok {{ {v} }} else {{ code.ip = {next}; *op_ip = {off}; {cold} }}",
            idx = r.index()
        ),
        None => format!(
            "match rd(regs, {}) {{ Val::Float(x) => x, _ => {{ code.ip = {next}; *op_ip = {off}; {cold} }} }}",
            reg(r)
        ),
    }
}

/// One `code.ip` arm inside the body's dispatch loop. `next` is the byte offset
/// of the following op — the value `code.ip` would hold after decoding this op,
/// which the specialized body must reproduce by hand since it never decodes.
/// Every `return` that leaves the body with `Err` or `Flow::Call` first stores
/// the op's offset into `*op_ip` for the driver's `locate`.
fn emit_op(w: &mut String, sh: &Sh, offset: usize, next: usize, op: &Op) {
    // The cold helpers (`bin_cold`, `branch_cold`) expect `code.ip` past the
    // op's operands — the interpreter's decode already did that for them — so
    // generated code sets it explicitly before tail-calling. `step` instead
    // wants `code.ip` *at* the op: it re-runs decode + arm wholesale.
    let mut s = String::new();
    macro_rules! wln {
        ($($t:tt)*) => {{ let _ = writeln!(s, $($t)*); }};
    }

    match op {
        Op::Move { dst, src } => {
            if let Some(d) = sh.int(*dst) {
                // Copy(src) in `int` requires src ∈ int too — propagate the
                // flag so a flag-false src poisons dst exactly as the copied
                // non-Int Val would
                let sflag = if sh.int(*src).is_some() {
                    format!("r{}ok", src.index())
                } else {
                    format!("matches!(rd(regs, {}), Val::Int(_))", reg(*src))
                };
                let sv = if sh.int(*src).is_some() {
                    format!("r{}i", src.index())
                } else {
                    format!(
                        "match rd(regs, {}) {{ Val::Int(x) => x, _ => 0 }}",
                        reg(*src)
                    )
                };
                wln!(
                    "{d} = {sv}; r{didx}ok = {sflag}; wr(regs, {}, rd(regs, {})); code.ip = {next};",
                    reg(*dst),
                    reg(*src),
                    didx = dst.index()
                );
            } else if let Some(d) = sh.float(*dst) {
                let sflag = if sh.float(*src).is_some() {
                    format!("r{}ok", src.index())
                } else {
                    format!("matches!(rd(regs, {}), Val::Float(_))", reg(*src))
                };
                let sv = if sh.float(*src).is_some() {
                    format!("r{}f", src.index())
                } else {
                    format!(
                        "match rd(regs, {}) {{ Val::Float(x) => x, _ => 0.0 }}",
                        reg(*src)
                    )
                };
                wln!(
                    "{d} = {sv}; r{didx}ok = {sflag}; wr(regs, {}, rd(regs, {})); code.ip = {next};",
                    reg(*dst),
                    reg(*src),
                    didx = dst.index()
                );
            } else {
                wln!(
                    "wr(regs, {}, rd(regs, {})); code.ip = {next};",
                    reg(*dst),
                    reg(*src)
                );
            }
        }
        Op::NewArray { dst } => {
            wln!(
                "wr(regs, {}, Val::Array(ctx.new_array(Vec::new()))); code.ip = {next};",
                reg(*dst)
            )
        }
        Op::NewDict { dst } => {
            wln!(
                "wr(regs, {}, Val::Dict(ctx.new_dict(DictMap::new()))); code.ip = {next};",
                reg(*dst)
            )
        }
        Op::NewInstance { dst, adt, fields } => {
            wln!("let fields = if {} <= INLINE_FIELDS {{", fields.len());
            wln!("    let mut data = [Val::Null; INLINE_FIELDS];");
            for (i, f) in fields.iter().enumerate() {
                wln!("    data[{i}] = rd(regs, {});", reg(*f));
            }
            wln!("    Fields::Inline {{ len: {}u8, data }}", fields.len());
            wln!("}} else {{");
            let fields = fields
                .iter()
                .map(|f| format!("rd(regs, {})", reg(*f)))
                .collect::<Vec<_>>()
                .join(", ");
            wln!("    Fields::Spilled(vec![{fields}])");
            wln!("}};");
            wln!(
                "wr(regs, {}, Val::Instance(ctx.new_instance({}u32, fields))); code.ip = {next};",
                reg(*dst),
                adt.index()
            );
        }
        Op::NewClosure {
            dst,
            body,
            captures,
        } => {
            let captures = captures
                .iter()
                .map(|c| format!("rd(regs, {})", reg(*c)))
                .collect::<Vec<_>>()
                .join(", ");
            wln!(
                "wr(regs, {}, Val::Closure(ctx.new_closure(BodyId::from({}u32), vec![{captures}]))); code.ip = {next};",
                reg(*dst),
                body.index()
            );
        }
        Op::Push { array, value } => {
            wln!("let arr = rd(regs, {}).as_array().unwrap();", reg(*array));
            wln!("let value = rd(regs, {});", reg(*value));
            wln!("arr.0.borrow_mut(&ctx).push(value);");
            wln!("code.ip = {next};");
        }
        Op::Insert { dict, key, value } => {
            wln!("let dict = rd(regs, {}).as_dict().unwrap();", reg(*dict));
            wln!(
                "let key = ctx.intern(strs.get(StrId::from({}u32)));",
                key.index()
            );
            wln!(
                "dict.0.borrow_mut(&ctx).insert(key, rd(regs, {}));",
                reg(*value)
            );
            wln!("code.ip = {next};");
        }
        Op::SetIndex { set, index, value } => {
            wln!("*op_ip = {offset};");
            wln!(
                "set_index(ctx, rd(regs, {}), rd(regs, {}), rd(regs, {}))?;",
                reg(*set),
                reg(*index),
                reg(*value)
            );
            wln!("code.ip = {next};");
        }
        Op::GetIndex {
            dst,
            set,
            index,
            kind,
        } => {
            wln!("*op_ip = {offset};");
            wln!(
                "let v = get_index(ctx, rd(regs, {}), rd(regs, {}), {})?;",
                reg(*set),
                reg(*index),
                access_kind(*kind)
            );
            wln!("wr(regs, {}, v); code.ip = {next};", reg(*dst));
        }
        Op::GetField {
            dst,
            src,
            slot,
            kind,
        } => {
            wln!("let receiver = rd(regs, {});", reg(*src));
            wln!(
                "if {} == AccessKind::Option && receiver == Val::Null {{",
                access_kind(*kind)
            );
            wln!("    wr(regs, {}, Val::Null); code.ip = {next};", reg(*dst));
            wln!("}} else {{");
            wln!("    let v = match receiver {{");
            wln!("        Val::Instance(i) => i.0.borrow().fields[{slot}],");
            wln!("        Val::Array(a) => a.0.borrow()[{slot}],");
            wln!("        Val::Null => {{ *op_ip = {offset}; return Err(RtErr::UnwrappedNull); }}");
            wln!(
                "        other => {{ *op_ip = {offset}; return Err(RtErr::Custom(format!(\"no fields on {{:?}}\", other.capture()))); }}"
            );
            wln!("    }};");
            wln!("    wr(regs, {}, v); code.ip = {next};", reg(*dst));
            wln!("}}");
        }
        Op::SetField {
            receiver,
            slot,
            value,
        } => {
            wln!("let receiver = rd(regs, {});", reg(*receiver));
            wln!("let value = rd(regs, {});", reg(*value));
            wln!("match receiver {{");
            wln!("    Val::Instance(i) => i.0.borrow_mut(&ctx).fields[{slot}] = value,");
            wln!("    Val::Array(a) => a.0.borrow_mut(&ctx)[{slot}] = value,");
            wln!("    Val::Null => {{ *op_ip = {offset}; return Err(RtErr::UnwrappedNull); }}");
            wln!(
                "    other => {{ *op_ip = {offset}; return Err(RtErr::Custom(format!(\"no fields on {{:?}}\", other.capture()))); }}"
            );
            wln!("}}");
            wln!("code.ip = {next};");
        }
        Op::LoadConst { dst, constant } => match (sh.int(*dst), sh.float(*dst)) {
            (Some(d), _) if matches!(constant, Constant::Int(_)) => {
                let Constant::Int(v) = constant else {
                    unreachable!()
                };
                wln!(
                    "{d} = {v}i64; r{}ok = true; wr(regs, {}, Val::Int({d})); code.ip = {next};",
                    dst.index(),
                    reg(*dst)
                );
            }
            (_, Some(d)) if matches!(constant, Constant::Float(_)) => {
                let Constant::Float(v) = constant else {
                    unreachable!()
                };
                wln!(
                    "{d} = f64::from_bits({}u64); r{}ok = true; wr(regs, {}, Val::Float({d})); code.ip = {next};",
                    v.to_bits(),
                    dst.index(),
                    reg(*dst)
                );
            }
            _ => {
                wln!(
                    "wr(regs, {}, constant_to_val({}, ctx, strs)); code.ip = {next};",
                    reg(*dst),
                    konst(constant)
                );
            }
        },
        Op::LoadBody { dst, body } => {
            wln!(
                "wr(regs, {}, Val::Fn(BodyId::from({}u32))); code.ip = {next};",
                reg(*dst),
                body.index()
            );
        }
        Op::LoadEntry { dst, slot } => {
            wln!("let base = frames.last().map(|f| f.base).unwrap_or(0);");
            wln!(
                "let v = unsafe {{ *regs.as_ptr().sub(base).add({}) }};",
                slot.index()
            );
            wln!("wr(regs, {}, v); code.ip = {next};", reg(*dst));
        }
        Op::StoreEntry { slot, src } => {
            wln!("let base = frames.last().map(|f| f.base).unwrap_or(0);");
            wln!("let v = rd(regs, {});", reg(*src));
            wln!(
                "unsafe {{ *regs.as_mut_ptr().sub(base).add({}) = v }};",
                slot.index()
            );
            wln!("code.ip = {next};");
        }
        Op::Jump { target } => wln!("code.ip = {};", tgt(target)),
        Op::JumpIf {
            cond,
            target,
            is_true,
        } => {
            wln!(
                "code.ip = if rd(regs, {}) == Val::Bool({is_true}) {{ {} }} else {{ {next} }};",
                reg(*cond),
                tgt(target)
            );
        }
        Op::ForNext { idx, bound, target } => {
            // shadowed-but-flag-clear falls back to `step`, whose arm hits the
            // same `unreachable!` the interpreter would
            let bail = format!("*op_ip = {offset}; return step(regs, code, ctx, strs, frames)");
            let i = match sh.int(*idx) {
                Some(v) => format!("if r{}ok {{ {v} }} else {{ {bail} }}", idx.index()),
                None => format!(
                    "match rd(regs, {}) {{ Val::Int(x) => x, _ => unreachable!(\"for_next idx is statically int\") }}",
                    reg(*idx)
                ),
            };
            let b = match sh.int(*bound) {
                Some(v) => format!("if r{}ok {{ {v} }} else {{ {bail} }}", bound.index()),
                None => format!(
                    "match rd(regs, {}) {{ Val::Int(x) => x, _ => unreachable!(\"for_next bound is statically int\") }}",
                    reg(*bound)
                ),
            };
            wln!("let i = {i} + 1;");
            if sh.int(*idx).is_some() {
                wln!(
                    "r{id}i = i; r{id}ok = true; wr(regs, {}, Val::Int(i));",
                    reg(*idx),
                    id = idx.index()
                );
            } else {
                wln!("wr(regs, {}, Val::Int(i));", reg(*idx));
            }
            wln!(
                "code.ip = if i < {b} {{ {} }} else {{ {next} }};",
                tgt(target)
            );
        }
        Op::Switch {
            scrut,
            base,
            default,
            table,
        } => {
            let table_src = table
                .iter()
                .map(|t| tgt(t).to_string())
                .collect::<Vec<_>>()
                .join(", ");
            wln!("code.ip = match rd(regs, {}) {{", reg(*scrut));
            wln!("    Val::Instance(i) => {{");
            wln!("        let idx = i.0.borrow().struct_id.wrapping_sub({base}u32) as usize;");
            wln!(
                "        if idx < {} {{ [{table_src}][idx] }} else {{ {} }}",
                table.len(),
                tgt(default)
            );
            wln!("    }}");
            wln!("    Val::Int(v) => {{");
            wln!("        let idx = v.wrapping_sub({base}i64);");
            wln!(
                "        if idx >= 0 && (idx as usize) < {} {{ [{table_src}][idx as usize] }} else {{ {} }}",
                table.len(),
                tgt(default)
            );
            wln!("    }}");
            wln!("    _ => {},", tgt(default));
            wln!("}};");
        }
        Op::Call { dst, callee, args } => {
            wln!("let target = match rd(regs, {}) {{", reg(*callee));
            wln!("    Val::Fn(b) => CallTarget::Value(b),");
            wln!("    Val::Closure(c) => CallTarget::Closure(c),");
            wln!("    other => {{ *op_ip = {offset}; return Err(not_callable(other)); }}");
            wln!("}};");
            wln!("let mut args = SmallVec::<[Val; 8]>::new();");
            for a in args {
                wln!("args.push(rd(regs, {}));", reg(*a));
            }
            // `enter_call` saves `code.ip` as the caller's resume slot — in the
            // interpreter it's already past this op's operands by then, so the
            // specialized arm must advance it before returning `Flow::Call`.
            wln!("code.ip = {next}; *op_ip = {offset};");
            wln!(
                "return Ok(Flow::Call {{ target, dst: {}, args }});",
                reg(*dst)
            );
        }
        Op::CallDirect { dst, body, args } => {
            wln!("let mut args = SmallVec::<[Val; 8]>::new();");
            for a in args {
                wln!("args.push(rd(regs, {}));", reg(*a));
            }
            wln!("code.ip = {next}; *op_ip = {offset};");
            wln!(
                "return Ok(Flow::Call {{ target: CallTarget::Fn(BodyId::from({}u32)), dst: {}, args }});",
                body.index(),
                reg(*dst)
            );
        }
        Op::CallNative { dst, id, args } => {
            wln!("let mut args = SmallVec::<[Val; 8]>::new();");
            for a in args {
                wln!("args.push(rd(regs, {}));", reg(*a));
            }
            wln!("let native = {{");
            wln!("    let table = ctx.state().natives.borrow();");
            wln!(
                "    *table.get({}).and_then(|o| o.as_ref()).expect(\"native id has no installed entry\")",
                id.index()
            );
            wln!("}};");
            // the interpreter's debug-mirror refresh runs with `code.ip` just
            // past this call op — `{next}` here, since generated code never decoded
            wln!("{{");
            wln!("    let mut stack = ctx.fixture::<DebugInfo>().stack.borrow_mut();");
            wln!("    stack.clear();");
            wln!("    stack.extend(frames.iter().map(|f| (f.chunk, f.ip as u32)));");
            wln!("    if let Some(top) = stack.last_mut() {{ top.1 = {next}u32; }}");
            wln!("}}");
            wln!("*op_ip = {offset};");
            wln!("let v = native.call(ctx, &args)?;");
            wln!("wr(regs, {}, v);", reg(*dst));
            wln!("code.ip = {next};");
        }
        Op::Return { val } => wln!("return Ok(Flow::Return(rd(regs, {})));", reg(*val)),
        Op::Panic {} => wln!("*op_ip = {offset}; return Err(RtErr::MatchPanicReached);"),
        Op::Raise { val } => {
            wln!(
                "let Val::Str(err) = rd(regs, {}) else {{ unreachable!(\"raise on a non-str value\") }};",
                reg(*val)
            );
            wln!("return Ok(Flow::Return(Val::Raised(err)));");
        }
        Op::IsRaised { dst, src } => {
            wln!(
                "wr(regs, {}, Val::Bool(matches!(rd(regs, {}), Val::Raised(_)))); code.ip = {next};",
                reg(*dst),
                reg(*src)
            );
        }
        Op::UnwrapRaised { dst, src } => {
            wln!(
                "let Val::Raised(err) = rd(regs, {}) else {{ unreachable!(\"UnwrapRaised on non-raised value\") }};",
                reg(*src)
            );
            wln!("wr(regs, {}, Val::Str(err)); code.ip = {next};", reg(*dst));
        }
        Op::Unwrap { dst, src } => {
            wln!("let v = rd(regs, {});", reg(*src));
            wln!("match v {{");
            wln!("    Val::Null => {{ *op_ip = {offset}; return Err(RtErr::UnwrappedNull); }}");
            wln!(
                "    Val::Raised(err) => {{ *op_ip = {offset}; return Err(RtErr::UnwrappedRaised(err.as_str().to_string())); }}"
            );
            wln!("    _ => wr(regs, {}, v),", reg(*dst));
            wln!("}}");
            wln!("code.ip = {next};");
        }
        Op::UnwrapUnit { dst, src } => {
            wln!("match rd(regs, {}) {{", reg(*src));
            wln!(
                "    Val::Raised(err) => {{ *op_ip = {offset}; return Err(RtErr::UnwrappedRaised(err.as_str().to_string())); }}"
            );
            wln!("    _ => wr(regs, {}, Val::Null),", reg(*dst));
            wln!("}}");
            wln!("code.ip = {next};");
        }
        Op::Len { dst, src } => {
            wln!("let len = match rd(regs, {}) {{", reg(*src));
            wln!("    Val::Array(a) => a.0.borrow().len(),");
            wln!("    Val::Dict(d) => d.0.borrow().len(),");
            wln!("    Val::Str(s) => s.as_str().chars().count(),");
            wln!("    Val::Int(i) => i as usize,");
            wln!(
                "    other => {{ *op_ip = {offset}; return Err(RtErr::Custom(format!(\"len: {{:?}} has no length\", other.capture()))); }}"
            );
            wln!("}};");
            if let Some(d) = sh.int(*dst) {
                wln!(
                    "{d} = len as i64; r{}ok = true; wr(regs, {}, Val::Int({d})); code.ip = {next};",
                    dst.index(),
                    reg(*dst)
                );
            } else {
                wln!(
                    "wr(regs, {}, Val::Int(len as i64)); code.ip = {next};",
                    reg(*dst)
                );
            }
        }
        Op::ToFloat { dst, src } => {
            let i = match sh.int(*src) {
                Some(v) => format!(
                    "if r{}ok {{ {v} }} else {{ *op_ip = {offset}; return step(regs, code, ctx, strs, frames) }}",
                    src.index()
                ),
                None => format!(
                    "match rd(regs, {}) {{ Val::Int(x) => x, _ => unreachable!(\"to_float can only be placed on an int by the compiler!\") }}",
                    reg(*src)
                ),
            };
            if let Some(d) = sh.float(*dst) {
                wln!(
                    "{d} = {i} as f64; r{}ok = true; wr(regs, {}, Val::Float({d})); code.ip = {next};",
                    dst.index(),
                    reg(*dst)
                );
            } else {
                wln!(
                    "wr(regs, {}, Val::Float({i} as f64)); code.ip = {next};",
                    reg(*dst)
                );
            }
        }
        Op::Sqrt { dst, src } => {
            let f = match sh.float(*src) {
                Some(v) => format!(
                    "if r{}ok {{ {v} }} else {{ *op_ip = {offset}; return step(regs, code, ctx, strs, frames) }}",
                    src.index()
                ),
                None => format!(
                    "match rd(regs, {}) {{ Val::Float(x) => x, _ => unreachable!(\"to_float can only be placed on a float by the compiler!\") }}",
                    reg(*src)
                ),
            };
            if let Some(d) = sh.float(*dst) {
                wln!(
                    "{d} = {f}.sqrt(); r{}ok = true; wr(regs, {}, Val::Float({d})); code.ip = {next};",
                    dst.index(),
                    reg(*dst)
                );
            } else {
                wln!(
                    "wr(regs, {}, Val::Float({f}.sqrt())); code.ip = {next};",
                    reg(*dst)
                );
            }
        }
        Op::In {
            dst,
            needle,
            haystack,
            condition,
        } => {
            wln!(
                "let v = contains(rd(regs, {}), rd(regs, {}), {condition});",
                reg(*needle),
                reg(*haystack)
            );
            wln!("wr(regs, {}, v); code.ip = {next};", reg(*dst));
        }
        Op::IsInstance { dst, src, adt } => {
            wln!(
                "let m = matches!(rd(regs, {}), Val::Instance(i) if i.0.borrow().struct_id == {}u32);",
                reg(*src),
                adt.index()
            );
            wln!("wr(regs, {}, Val::Bool(m)); code.ip = {next};", reg(*dst));
        }
        Op::Format { dst, parts } => {
            wln!("let mut text = String::with_capacity(32);");
            for p in parts {
                match p {
                    OpFormatPart::Literal(id) => {
                        wln!("text.push_str(strs.get(StrId::from({}u32)));", id.index())
                    }
                    OpFormatPart::Value(r) => {
                        wln!("*op_ip = {offset};");
                        wln!("ctx.to_string_into(&mut text, rd(regs, {}))?;", reg(*r));
                    }
                }
            }
            wln!(
                "wr(regs, {}, Val::Str(ctx.intern(&text))); code.ip = {next};",
                reg(*dst)
            );
        }
        Op::Bin {
            dst,
            left,
            op,
            right,
        } => {
            wln!("*op_ip = {offset};");
            wln!(
                "let v = bin(rd(regs, {}), ctx, rd(regs, {}), BinOp::{op:?})?;",
                reg(*left),
                reg(*right)
            );
            wln!("wr(regs, {}, v); code.ip = {next};", reg(*dst));
        }
        Op::Unary { dst, op, src } => {
            wln!("*op_ip = {offset};");
            wln!(
                "let v = unary(rd(regs, {}), ctx, UnaryOp::{op:?})?;",
                reg(*src)
            );
            wln!("wr(regs, {}, v); code.ip = {next};", reg(*dst));
        }
        Op::BoolEq { dst, left, right } => emit_bool(&mut s, *dst, *left, *right, next, "=="),
        Op::BoolNe { dst, left, right } => emit_bool(&mut s, *dst, *left, *right, next, "!="),
        Op::AddInt { dst, left, right } => emit_int_arith(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            "checked_add",
            "Add",
        ),
        Op::SubInt { dst, left, right } => emit_int_arith(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            "checked_sub",
            "Sub",
        ),
        Op::MultInt { dst, left, right } => emit_int_arith(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            "checked_mul",
            "Mult",
        ),
        Op::ModInt { dst, left, right } => {
            let cold = format!(
                "return bin_cold(regs, {}, {}, {}, ctx, BinOp::Mod);",
                reg(*dst),
                reg(*left),
                reg(*right)
            );
            let a = int_opnd(sh, *left, next, offset, &cold);
            let b = int_opnd(sh, *right, next, offset, &cold);
            wln!("let b = {b};");
            wln!("if b == 0 {{ *op_ip = {offset}; return Err(RtErr::ModByZero); }}");
            if let Some(d) = sh.int(*dst) {
                wln!(
                    "{d} = {a} % b; r{}ok = true; wr(regs, {}, Val::Int({d})); code.ip = {next};",
                    dst.index(),
                    reg(*dst)
                );
            } else {
                wln!(
                    "wr(regs, {}, Val::Int({a} % b)); code.ip = {next};",
                    reg(*dst)
                );
            }
        }
        Op::IntLt { dst, left, right } => emit_int_eval(
            &mut s, sh, offset, *dst, *left, *right, next, "<", "LessThan",
        ),
        Op::IntLe { dst, left, right } => emit_int_eval(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            "<=",
            "LessEqual",
        ),
        Op::IntGt { dst, left, right } => emit_int_eval(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            ">",
            "GreaterThan",
        ),
        Op::IntGe { dst, left, right } => emit_int_eval(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            ">=",
            "GreaterEqual",
        ),
        Op::IntEq { dst, left, right } => emit_int_eval(
            &mut s, sh, offset, *dst, *left, *right, next, "==", "Identity",
        ),
        Op::IntNe { dst, left, right } => emit_int_eval(
            &mut s, sh, offset, *dst, *left, *right, next, "!=", "NotEqual",
        ),
        Op::AddFloat { dst, left, right } => {
            emit_float_arith(&mut s, sh, offset, *dst, *left, *right, next, "+", "Add")
        }
        Op::SubFloat { dst, left, right } => {
            emit_float_arith(&mut s, sh, offset, *dst, *left, *right, next, "-", "Sub")
        }
        Op::MultFloat { dst, left, right } => {
            emit_float_arith(&mut s, sh, offset, *dst, *left, *right, next, "*", "Mult")
        }
        Op::DivFloat { dst, left, right } => {
            emit_float_arith(&mut s, sh, offset, *dst, *left, *right, next, "/", "Div")
        }
        Op::FloatLt { dst, left, right } => emit_float_eval(
            &mut s, sh, offset, *dst, *left, *right, next, "<", "LessThan",
        ),
        Op::FloatLe { dst, left, right } => emit_float_eval(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            "<=",
            "LessEqual",
        ),
        Op::FloatGt { dst, left, right } => emit_float_eval(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            ">",
            "GreaterThan",
        ),
        Op::FloatGe { dst, left, right } => emit_float_eval(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *right,
            next,
            ">=",
            "GreaterEqual",
        ),
        Op::FloatEq { dst, left, right } => emit_float_eval(
            &mut s, sh, offset, *dst, *left, *right, next, "==", "Identity",
        ),
        Op::FloatNe { dst, left, right } => emit_float_eval(
            &mut s, sh, offset, *dst, *left, *right, next, "!=", "NotEqual",
        ),
        Op::StrEq { dst, left, right } => {
            emit_str_eval(&mut s, offset, *dst, *left, *right, next, "==", "Identity")
        }
        Op::StrNe { dst, left, right } => {
            emit_str_eval(&mut s, offset, *dst, *left, *right, next, "!=", "NotEqual")
        }
        Op::AddIntImm { dst, left, val } => emit_int_arith_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            "checked_add",
            "Add",
        ),
        Op::SubIntImm { dst, left, val } => emit_int_arith_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            "checked_sub",
            "Sub",
        ),
        Op::MultIntImm { dst, left, val } => emit_int_arith_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            "checked_mul",
            "Mult",
        ),
        Op::ModIntImm { dst, left, val } => {
            let a = int_opnd(
                sh,
                *left,
                next,
                offset,
                &format!(
                    "return bin_cold_imm_int(regs, {}, {}, {val}i64, ctx, BinOp::Mod);",
                    reg(*dst),
                    reg(*left)
                ),
            );
            wln!("if {val}i64 == 0 {{ *op_ip = {offset}; return Err(RtErr::ModByZero); }}");
            if let Some(d) = sh.int(*dst) {
                wln!(
                    "{d} = {a} % {val}i64; r{}ok = true; wr(regs, {}, Val::Int({d})); code.ip = {next};",
                    dst.index(),
                    reg(*dst)
                );
            } else {
                wln!(
                    "wr(regs, {}, Val::Int({a} % {val}i64)); code.ip = {next};",
                    reg(*dst)
                );
            }
        }
        Op::IntLtImm { dst, left, val } => {
            emit_int_eval_imm(&mut s, sh, offset, *dst, *left, *val, next, "<", "LessThan")
        }
        Op::IntLeImm { dst, left, val } => emit_int_eval_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            "<=",
            "LessEqual",
        ),
        Op::IntGtImm { dst, left, val } => emit_int_eval_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            ">",
            "GreaterThan",
        ),
        Op::IntGeImm { dst, left, val } => emit_int_eval_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            ">=",
            "GreaterEqual",
        ),
        Op::IntEqImm { dst, left, val } => emit_int_eval_imm(
            &mut s, sh, offset, *dst, *left, *val, next, "==", "Identity",
        ),
        Op::IntNeImm { dst, left, val } => emit_int_eval_imm(
            &mut s, sh, offset, *dst, *left, *val, next, "!=", "NotEqual",
        ),
        Op::BIntLt {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Int",
            "<",
            "LessThan",
        ),
        Op::BIntLe {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Int",
            "<=",
            "LessEqual",
        ),
        Op::BIntGt {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Int",
            ">",
            "GreaterThan",
        ),
        Op::BIntGe {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Int",
            ">=",
            "GreaterEqual",
        ),
        Op::BIntEq {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Int",
            "==",
            "Identity",
        ),
        Op::BIntNe {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Int",
            "!=",
            "NotEqual",
        ),
        Op::BIntLtImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, false)),
            *is_true,
            "Val::Int",
            "<",
            "LessThan",
        ),
        Op::BIntLeImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, false)),
            *is_true,
            "Val::Int",
            "<=",
            "LessEqual",
        ),
        Op::BIntGtImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, false)),
            *is_true,
            "Val::Int",
            ">",
            "GreaterThan",
        ),
        Op::BIntGeImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, false)),
            *is_true,
            "Val::Int",
            ">=",
            "GreaterEqual",
        ),
        Op::BIntEqImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, false)),
            *is_true,
            "Val::Int",
            "==",
            "Identity",
        ),
        Op::BIntNeImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, false)),
            *is_true,
            "Val::Int",
            "!=",
            "NotEqual",
        ),
        Op::BFloatLt {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Float",
            "<",
            "LessThan",
        ),
        Op::BFloatLe {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Float",
            "<=",
            "LessEqual",
        ),
        Op::BFloatGt {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Float",
            ">",
            "GreaterThan",
        ),
        Op::BFloatGe {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Float",
            ">=",
            "GreaterEqual",
        ),
        Op::BFloatEq {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Float",
            "==",
            "Identity",
        ),
        Op::BFloatNe {
            target,
            left,
            right,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            Some(*right),
            None,
            *is_true,
            "Val::Float",
            "!=",
            "NotEqual",
        ),
        Op::BFloatLtImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, true)),
            *is_true,
            "Val::Float",
            "<",
            "LessThan",
        ),
        Op::BFloatLeImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, true)),
            *is_true,
            "Val::Float",
            "<=",
            "LessEqual",
        ),
        Op::BFloatGtImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, true)),
            *is_true,
            "Val::Float",
            ">",
            "GreaterThan",
        ),
        Op::BFloatGeImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, true)),
            *is_true,
            "Val::Float",
            ">=",
            "GreaterEqual",
        ),
        Op::BFloatEqImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, true)),
            *is_true,
            "Val::Float",
            "==",
            "Identity",
        ),
        Op::BFloatNeImm {
            target,
            left,
            val,
            is_true,
        } => emit_branch(
            &mut s,
            sh,
            offset,
            next,
            target,
            *left,
            None,
            Some((*val, true)),
            *is_true,
            "Val::Float",
            "!=",
            "NotEqual",
        ),
        Op::AddFloatImm { dst, left, val } => {
            emit_float_arith_imm(&mut s, sh, offset, *dst, *left, *val, next, "+", "Add")
        }
        Op::SubFloatImm { dst, left, val } => {
            emit_float_arith_imm(&mut s, sh, offset, *dst, *left, *val, next, "-", "Sub")
        }
        Op::MultFloatImm { dst, left, val } => {
            emit_float_arith_imm(&mut s, sh, offset, *dst, *left, *val, next, "*", "Mult")
        }
        Op::ModFloatImm { dst, left, val } => {
            emit_float_arith_imm(&mut s, sh, offset, *dst, *left, *val, next, "%", "Mod")
        }
        Op::FloatLtImm { dst, left, val } => {
            emit_float_eval_imm(&mut s, sh, offset, *dst, *left, *val, next, "<", "LessThan")
        }
        Op::FloatLeImm { dst, left, val } => emit_float_eval_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            "<=",
            "LessEqual",
        ),
        Op::FloatGtImm { dst, left, val } => emit_float_eval_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            ">",
            "GreaterThan",
        ),
        Op::FloatGeImm { dst, left, val } => emit_float_eval_imm(
            &mut s,
            sh,
            offset,
            *dst,
            *left,
            *val,
            next,
            ">=",
            "GreaterEqual",
        ),
        Op::FloatEqImm { dst, left, val } => emit_float_eval_imm(
            &mut s, sh, offset, *dst, *left, *val, next, "==", "Identity",
        ),
        Op::FloatNeImm { dst, left, val } => emit_float_eval_imm(
            &mut s, sh, offset, *dst, *left, *val, next, "!=", "NotEqual",
        ),
    }
    let _ = writeln!(w, "            {offset} => {{");
    let _ = write!(w, "{s}");
    let _ = writeln!(w, "            }}");
}

fn emit_bool(s: &mut String, dst: Reg, left: Reg, right: Reg, next: usize, op: &str) {
    let name = if op == "==" { "eq" } else { "ne" };
    let _ = writeln!(
        s,
        "let Val::Bool(l) = rd(regs, {}) else {{ unreachable!(\"illegal bool {name} op\") }};\n\
         let Val::Bool(r) = rd(regs, {}) else {{ unreachable!(\"illegal bool {name} op\") }};\n\
         wr(regs, {}, Val::Bool(l {op} r)); code.ip = {next};",
        reg(left),
        reg(right),
        reg(dst),
    );
}

// Below, the emit_* fns write the arm's *contents* into `s` and `emit_op` wraps
// it in `{offset} => {{ ... }}`. Operand expressions come from `int_opnd` /
// `float_opnd`: a shadow-local name when unboxed, else a `regs` match whose
// miss arm pre-advances `code.ip`, stores `*op_ip`, and tail-calls the same
// `bin_cold*`/`branch_cold*` helper the interpreter's macro would have reached.

#[allow(clippy::too_many_arguments)]
fn emit_int_arith(
    s: &mut String,
    sh: &Sh,
    off: usize,
    dst: Reg,
    left: Reg,
    right: Reg,
    next: usize,
    checked: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold(regs, {}, {}, {}, ctx, BinOp::{binop});",
        reg(dst),
        reg(left),
        reg(right)
    );
    let a = int_opnd(sh, left, next, off, &cold);
    let b = int_opnd(sh, right, next, off, &cold);
    let _ = writeln!(
        s,
        "let Some(v) = ({a}).{checked}({b}) else {{ *op_ip = {off}; return Err(RtErr::IntegerOverflow) }};"
    );
    sh.wr_shadow(s, dst, "Int", "v");
    let _ = writeln!(s, "code.ip = {next};");
}

#[allow(clippy::too_many_arguments)]
fn emit_int_eval(
    s: &mut String,
    sh: &Sh,
    off: usize,
    dst: Reg,
    left: Reg,
    right: Reg,
    next: usize,
    op: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold(regs, {}, {}, {}, ctx, BinOp::{binop});",
        reg(dst),
        reg(left),
        reg(right)
    );
    let a = int_opnd(sh, left, next, off, &cold);
    let b = int_opnd(sh, right, next, off, &cold);
    let _ = writeln!(
        s,
        "wr(regs, {}, Val::Bool({a} {op} {b})); code.ip = {next};",
        reg(dst)
    );
}

#[allow(clippy::too_many_arguments)]
fn emit_float_arith(
    s: &mut String,
    sh: &Sh,
    off: usize,
    dst: Reg,
    left: Reg,
    right: Reg,
    next: usize,
    op: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold(regs, {}, {}, {}, ctx, BinOp::{binop});",
        reg(dst),
        reg(left),
        reg(right)
    );
    let a = float_opnd(sh, left, next, off, &cold);
    let b = float_opnd(sh, right, next, off, &cold);
    sh.wr_shadow(s, dst, "Float", &format!("({a}) {op} ({b})"));
    let _ = writeln!(s, "code.ip = {next};");
}

#[allow(clippy::too_many_arguments)]
fn emit_float_eval(
    s: &mut String,
    sh: &Sh,
    off: usize,
    dst: Reg,
    left: Reg,
    right: Reg,
    next: usize,
    op: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold(regs, {}, {}, {}, ctx, BinOp::{binop});",
        reg(dst),
        reg(left),
        reg(right)
    );
    let a = float_opnd(sh, left, next, off, &cold);
    let b = float_opnd(sh, right, next, off, &cold);
    let _ = writeln!(
        s,
        "wr(regs, {}, Val::Bool({a} {op} {b})); code.ip = {next};",
        reg(dst)
    );
}

fn emit_str_eval(
    s: &mut String,
    off: usize,
    dst: Reg,
    left: Reg,
    right: Reg,
    next: usize,
    op: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold(regs, {}, {}, {}, ctx, BinOp::{binop});",
        reg(dst),
        reg(left),
        reg(right)
    );
    let _ = writeln!(
        s,
        "match (rd(regs, {l}), rd(regs, {r})) {{\n\
         (Val::Str(a), Val::Str(b)) => {{ wr(regs, {d}, Val::Bool(a {op} b)); code.ip = {next}; }}\n\
         _ => {{ code.ip = {next}; *op_ip = {off}; {cold} }}\n\
         }}",
        l = reg(left),
        r = reg(right),
        d = reg(dst),
    );
}

#[allow(clippy::too_many_arguments)]
fn emit_int_arith_imm(
    s: &mut String,
    sh: &Sh,
    off: usize,
    dst: Reg,
    left: Reg,
    val: i64,
    next: usize,
    checked: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold_imm_int(regs, {}, {}, {val}i64, ctx, BinOp::{binop});",
        reg(dst),
        reg(left)
    );
    let a = int_opnd(sh, left, next, off, &cold);
    let _ = writeln!(
        s,
        "let Some(v) = ({a}).{checked}({val}i64) else {{ *op_ip = {off}; return Err(RtErr::IntegerOverflow) }};"
    );
    sh.wr_shadow(s, dst, "Int", "v");
    let _ = writeln!(s, "code.ip = {next};");
}

#[allow(clippy::too_many_arguments)]
fn emit_int_eval_imm(
    s: &mut String,
    sh: &Sh,
    off: usize,
    dst: Reg,
    left: Reg,
    val: i64,
    next: usize,
    op: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold_imm_int(regs, {}, {}, {val}i64, ctx, BinOp::{binop});",
        reg(dst),
        reg(left)
    );
    let a = int_opnd(sh, left, next, off, &cold);
    let _ = writeln!(
        s,
        "wr(regs, {}, Val::Bool({a} {op} {val}i64)); code.ip = {next};",
        reg(dst)
    );
}

#[allow(clippy::too_many_arguments)]
fn emit_float_arith_imm(
    s: &mut String,
    sh: &Sh,
    off: usize,
    dst: Reg,
    left: Reg,
    val: i64,
    next: usize,
    op: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold_imm_float(regs, {}, {}, f64::from_bits({val}i64 as u64), ctx, BinOp::{binop});",
        reg(dst),
        reg(left)
    );
    let a = float_opnd(sh, left, next, off, &cold);
    sh.wr_shadow(
        s,
        dst,
        "Float",
        &format!("({a}) {op} f64::from_bits({val}i64 as u64)"),
    );
    let _ = writeln!(s, "code.ip = {next};");
}

#[allow(clippy::too_many_arguments)]
fn emit_float_eval_imm(
    s: &mut String,
    sh: &Sh,
    off: usize,
    dst: Reg,
    left: Reg,
    val: i64,
    next: usize,
    op: &str,
    binop: &str,
) {
    let cold = format!(
        "return bin_cold_imm_float(regs, {}, {}, f64::from_bits({val}i64 as u64), ctx, BinOp::{binop});",
        reg(dst),
        reg(left)
    );
    let a = float_opnd(sh, left, next, off, &cold);
    let _ = writeln!(
        s,
        "wr(regs, {}, Val::Bool({a} {op} f64::from_bits({val}i64 as u64))); code.ip = {next};",
        reg(dst)
    );
}

/// The `B*` branch family — `right` for the register variant, `imm` for the
/// immediate one (`is_float` picks the `f64::from_bits` decode). A mismatched
/// operand type pre-advances `code.ip` and tail-calls the `branch_cold*`
/// helper the interpreter's own macro would have reached.
#[allow(clippy::too_many_arguments)]
fn emit_branch(
    s: &mut String,
    sh: &Sh,
    off: usize,
    next: usize,
    target: &BlockTarget,
    left: Reg,
    right: Option<Reg>,
    imm: Option<(i64, bool)>,
    is_true: bool,
    variant: &str,
    op: &str,
    binop: &str,
) {
    let t = tgt(target);
    let int = variant == "Val::Int";
    let hit = if let Some(r) = right {
        let cold = format!(
            "return branch_cold(regs, code, {t}, {is_true}, {}, {}, ctx, BinOp::{binop});",
            reg(left),
            reg(r)
        );
        let a = if int {
            int_opnd(sh, left, next, off, &cold)
        } else {
            float_opnd(sh, left, next, off, &cold)
        };
        let b = if int {
            int_opnd(sh, r, next, off, &cold)
        } else {
            float_opnd(sh, r, next, off, &cold)
        };
        format!("{a} {op} {b}")
    } else if let Some((val, true)) = imm {
        let cold = format!(
            "return branch_cold_imm_float(regs, code, {t}, {is_true}, {}, f64::from_bits({val}i64 as u64), ctx, BinOp::{binop});",
            reg(left)
        );
        let a = float_opnd(sh, left, next, off, &cold);
        format!("{a} {op} f64::from_bits({val}i64 as u64)")
    } else {
        let (val, _) = imm.unwrap();
        let cold = format!(
            "return branch_cold_imm_int(regs, code, {t}, {is_true}, {}, {val}i64, ctx, BinOp::{binop});",
            reg(left)
        );
        let a = int_opnd(sh, left, next, off, &cold);
        format!("{a} {op} {val}i64")
    };
    let _ = writeln!(s, "let hit = {hit};");
    let _ = writeln!(
        s,
        "code.ip = if hit == {is_true} {{ {t} }} else {{ {next} }};"
    );
}
